-- Batch 10 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Alexir Packaging', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Roman Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Tams Packaging Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('On The Vine', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Jadan Press Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Drayton Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The High Arcal School', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Traybond Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Worcester Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Claridges Copy & Print Warwick', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Menzies Design & Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('United Kingdom Atomic Energy Authority', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Excelsior Graphic Designers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Sunny Digital Prints', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('London Graphics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('City Screen Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Kall Kwik Birmingham', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Sanders Print People', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Rotary Printers (stourport) Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('D3 Creative', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ace Digital', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Impression Design & Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('South Bucks Business Products', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Harwell Labels', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Discount Displays', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Toad Diaries', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('4pm Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printconcern', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Carfax Cards Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Grayson Design & Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Stormdfx Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Arbor Print Management Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Small Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Mail House', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Thomas Fattorini Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Heron Dawson & Sawyer', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Proimage', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Lydia Digital Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Halcyon of Bushey', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Gartree Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Midland Trade Stringing Service Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('AllDigital Solutions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Chris Cook Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('XLPress', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ont', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Just Personalised Prints Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Greenleafcrafts', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Pingles Publishing', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Apple Print & Creative Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Printing Chambers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Heron Jader Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Minuteman Press Nottingham', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bartec Paper & Packaging Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('East Midlands Print Company', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Lear Stationers & Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Team Tea', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bolton Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Vincent Publishing Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Wiseprint Solutions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Evolution Print & Design Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('UNIQUE DIGITAL & PRINTERS LTD', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Crownhills School', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Publicity Plastics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('W T Lynn Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Great British Printhouse', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mailing Guy', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Joshua Horgan Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('2Leavestudio', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cut Above', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('I Design Signs', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Franco Group UK', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cranfield University', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('University of Surrey', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mbobanjack Enterprise', 'prospect', 'pipedrive_import_2025', 'Gambia', 'active', 'Steve Humphreys'),
  ('Socos Teo', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Clandeboye Printing services', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Hish Printing Services', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Mailmate Print', 'prospect', 'pipedrive_import_2025', 'Jersey', 'active', 'Steve Humphreys'),
  ('Splash Frog', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Aspect Media', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Priory Press', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Zing Design & Print', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Creative Zoo', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Mourne Office Supplies', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Graphic Answers', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Cartridges Inc.', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('DJ Print Ltd', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('David Mahon Properties', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Victor Stationery', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Northside Graphics Ltd', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('DMC Design', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Colour Copy Services', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Regency Print And Display', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('James Hamilton & Co (Lurgan) Ltd', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Sparks In Colour', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Darwin Press Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Media Design and Print', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Pico Studios', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Ream Ltd', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('The Orchardville Business Centre', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



