-- Batch 19 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Congreat Printing Factory', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('CONTITECH PRINT SERVICE (S) PTE LTD', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Copigraf', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Copiepresse', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Colors & More', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', 'Steve Humphreys'),
  ('Copy Centre, Angolia', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Copulous Media', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Copy General', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('Copy Top', 'prospect', 'pipedrive_import_2025', 'Kindom of Bahrain', 'active', 'Steve Humphreys'),
  ('Copycat', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('CopyCat Drammen', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CopyCat Head Office', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Condor Kartong AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Copyshop Groenlo', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('CopyTech Smart Business Solutions', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Copyworld (Pty) Ltd', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Copyzoom', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Core Dumamics Multimedia', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Corodex Agencies Co. L.L.C', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Corporaci�n Morales Grupo Creativo', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Corporacion Mundo Grafic', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Cosmo Print Solutions Pvt Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Corprensa', 'prospect', 'pipedrive_import_2025', 'Panama', 'active', 'Steve Humphreys'),
  ('Contact Printing Press', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Costa Printing Press', 'prospect', 'pipedrive_import_2025', 'Kuwait', 'active', 'Steve Humphreys'),
  ('CPD Advertising Solution', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('CPNF', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('CPI BRODARD & TAUPIN', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Creaciones A&M', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Creative Art Makers', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Creative Art Print Service', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Creative Concepts', 'prospect', 'pipedrive_import_2025', 'Namibia', 'active', 'Steve Humphreys'),
  ('Copy shop Bergen AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Creative Design & Print', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Creative Digital', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Creative Graphics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Creative Plus Designs', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Creative Vision Holdings Ltd', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Creatives Digital Print', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('CREATIVIDAD PROMOCIONAL', 'prospect', 'pipedrive_import_2025', 'MEXICO', 'active', 'Steve Humphreys'),
  ('CREATIX', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Cristiane', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Cromopolis', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('CopyCat Billingstad', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CROMATIK PRESS', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Crossbow Print Centre (L.L.C.)', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Crosshatch Media ltd', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Crown Prince Court', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('CopyCat Fornebu', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CopyCat Nydalen', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CopyCat Posthuset', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CopyCat Sentrum', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CopyCat Ski', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CopyCat Trondheim', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CopyGraf AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Creaffica Dise�o e Impresi�n', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', 'Steve Humphreys'),
  ('Creative H�ssleholm', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Creative Print Sverige AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Crimson', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Crystalpp.com', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', 'Steve Humphreys'),
  ('CRYSTAL PRINTING PRESS', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', 'Steve Humphreys'),
  ('Crown printing', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Crownwise Investments Limited', 'prospect', 'pipedrive_import_2025', 'Zambia', 'active', 'Steve Humphreys'),
  ('C-SOLUTION', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('CuDrag.md', 'prospect', 'pipedrive_import_2025', 'Moldova', 'active', 'Steve Humphreys'),
  ('Cuquipando srl', 'prospect', 'pipedrive_import_2025', 'Uruguay', 'active', 'Steve Humphreys'),
  ('Custom Printz', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cyan digital printing', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Custom Sign Designs', 'prospect', 'pipedrive_import_2025', 'Trinidad and Tobago', 'active', 'Steve Humphreys'),
  ('Cybak Industrial Group', 'prospect', 'pipedrive_import_2025', 'Iran', 'active', 'Steve Humphreys'),
  ('D,jureviciaus imone', 'prospect', 'pipedrive_import_2025', 'Lithuania', 'active', 'Steve Humphreys'),
  ('D.M. Center', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('Dakroub', 'prospect', 'pipedrive_import_2025', 'lebanon', 'active', 'Steve Humphreys'),
  ('Dakhya print and advertising', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Dala Tryckeri', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Daisy Medical', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('D2 Print Ltd', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Damen Drukkers', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('D2 Productions AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Damix Ventures Ltd', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Dandy Dots', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Dangerous Media Malaysia', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('Danko', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('Danone', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Dansk Supermarked Group', 'prospect', 'pipedrive_import_2025', 'Denmark', 'active', 'Steve Humphreys'),
  ('Dao Anh Nhat', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('Dar Akhbar Al Khaleej', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', 'Steve Humphreys'),
  ('Dar Al Andalus Printing Pub. & Dist. LLC', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Dar Al Likaa', 'prospect', 'pipedrive_import_2025', 'Iraq', 'active', 'Steve Humphreys'),
  ('Dale Gudbrands trykkeri AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Dar Al Fajr Printing & Publishing', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Dar Al Qabas Press, Printing & Publish', 'prospect', 'pipedrive_import_2025', 'Kuwait', 'active', 'Steve Humphreys'),
  ('Dar el Founoun s a l', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Dar Elbadr', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('Dar reyadah publishing', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Dark Transmissions', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('DAST s.r.o.', 'prospect', 'pipedrive_import_2025', 'Slovakia', 'active', 'Steve Humphreys'),
  ('Darpan Publications International Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Data Cream ky', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Daniel Engen Productions', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



