-- Batch 3 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Hartung', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Jetprint', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Tysonprint', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Reflex Labels', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bishop Grosseteste University', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Arch 5 Design', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Colorworld', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Corner House', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Prontaprint (Stratford)', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Clifton Print Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Diguru Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Iansprint Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Matin Prime', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Universal Design & Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Alina Powell', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Smithers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Olympus Labels Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Almac', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Clinical Print Finishers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Opal Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Minuteman Press', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('BPG', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mr Colle', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Access Print Copy & Design Co', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Willow Attic', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Hammond Gower', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Delphis Eco', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Pipedream Design', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Alpha Graphics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Tracks Publishing Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Gee Bros', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Quality Print Plus Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('AK Products', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('ACL Packaging Print Division', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('CM Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Publicity & Display Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Office Products International Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Andrew Joseph Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Marshall Signs', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Sherrens', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Greywell Press Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Acacia Graphix Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Razammataz', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Fountain Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Wates', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Watershed Packaging Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Lucilla Lavender Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Instaprint', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('AMP', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Twenty Four Seven Design & Prints', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Swift Design & Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Craven Design & Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('NETPRINTERS', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('london envelopes ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Argun Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('BUDGET SIGNS LIMITED', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Liquid Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('SIPEXA LTD', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Compass Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Guildbourne Printing Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Shopnation', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Service Press Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mdl Kelex Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('RAD Printing Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Hayman Creative', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Reel Appeal', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Route1Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Britannia Garment Packaging', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printworks', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Norfolk Print & Design', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print Finishing Specialities', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Melody Studio', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('FM Litho', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Hine Labels Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('R B Print Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Potato Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cawthornes', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Beyond the Veil', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Masterprint', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Alpha Duplication Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Rowson Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('3di', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Abbey Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('First Impressions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bow Design and Print Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Outstanding Md Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bonacia', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Royal Academy of Music', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Borney Uk Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Mailing People', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cartridges Inc', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Central Press', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('Printland', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Election Workshop', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Joma Jewellery', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Langtec', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Adare SEC', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Blissetts', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Chris Cook Print & Office Supplies', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('ecoMLR Ltd.', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



