-- Batch 42 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('George Wilson', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Gordon Kell', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Gregg Robinson', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', 'Steve Humphreys'),
  ('Hammad I. Alhammad', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Hardian Lorens', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Harish Kumar', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Hary Iman', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Hatem  Balegi', 'prospect', 'pipedrive_import_2025', 'Tunisia', 'active', 'Steve Humphreys'),
  ('Harsha Nayuni', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Herson Favis', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Hemant', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Hesham Gouda', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Hezi Keshet', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Ian O''Driscoll', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('inkagraphiceditora@gmail.com', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Ivan Espinoza', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', 'Steve Humphreys'),
  ('Ivano Rizzo', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Javier Baladron', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Iyanar Ramapuli', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jacobs', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Jean-Claude', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Jejo Jacob', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Jo�o Chirnev', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Jiri Sloupensky', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', 'Steve Humphreys'),
  ('Joao Santos', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Jobi Chan', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Johan Mosq', 'prospect', 'pipedrive_import_2025', 'Latvia', 'active', 'Steve Humphreys'),
  ('Joel Daniel', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', 'Steve Humphreys'),
  ('John Smyth', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Jon Doe', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Joon Jo', 'prospect', 'pipedrive_import_2025', 'Korea', 'active', 'Steve Humphreys'),
  ('Jos� Carlos Ram�rez Pacheco', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Jones Frank', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jose Chacon', 'prospect', 'pipedrive_import_2025', 'Venezuela', 'active', 'Steve Humphreys'),
  ('Josip Rajkovic', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('''joshua_cz@hotm, ail.com''', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Jose Miguel Salazar', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Juliet Mphanyane', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Julius Katamba', 'prospect', 'pipedrive_import_2025', 'Uganda', 'active', 'Steve Humphreys'),
  ('Junichi Iwao', 'prospect', 'pipedrive_import_2025', 'Japan', 'active', 'Steve Humphreys'),
  ('Kamel Amrioui', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Kamel Bekkar', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('kirit bavishiya', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Klea Alliaj', 'prospect', 'pipedrive_import_2025', 'Albania', 'active', 'Steve Humphreys'),
  ('Kolawole Elegbede', 'prospect', 'pipedrive_import_2025', 'Benin', 'active', 'Steve Humphreys'),
  ('Lance Pettit', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Lahcen Benssi', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Lay Naik', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Lara', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('leeann lilo', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Linda Kempster', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Luis Salazar', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Luis Ferrer', 'prospect', 'pipedrive_import_2025', 'Puerto Rico', 'active', 'Steve Humphreys'),
  ('Linlada Niwattanachok', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Luqmann Ismail', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Macarena Riveros', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Mahesh Kumar', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Makaddesh', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('''malcalau@hotma, il.com''', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Manish', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Manzoor ilahi khan', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Mansoor Khan', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Mansi Rao', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Manuel Pinheiro', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Marcel de Boer', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Marko Petek', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Marcelsoca', 'prospect', 'pipedrive_import_2025', 'Uruguay', 'active', 'Steve Humphreys'),
  ('Matt Tagle', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Mary Pancho', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Maroua Belorhmari', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('M�y in Th�nh Th?ng', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('Mayank', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Mei Ann Adriano Sudiacal', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Michael lindley', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('M�ngcheng', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('mohamed lalem', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Mohamed Shafie', 'prospect', 'pipedrive_import_2025', 'Sudan', 'active', 'Steve Humphreys'),
  ('Mohammed', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', 'Steve Humphreys'),
  ('Mohamedraza Somji', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('MOHAMMED ALI Chalil', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Mohammed Afsal', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Mohammed Alkafarna', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Mr Ait Messaoud Fouad', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('Mufaddal Fatehi', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Mumu', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Muthalib Parambath', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', 'Steve Humphreys'),
  ('Mustafa S�zer', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Natalija Kuzeva', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Muyiwa Williams', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Nabil Raja', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Nadia Monnier', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('N.R. Jayaraman', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Nathaniel Compass', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Naveen Kumar', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Nayef Ram', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ngozi Haynes', 'prospect', 'pipedrive_import_2025', 'Guyana', 'active', 'Steve Humphreys'),
  ('Nelson Cruz', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Nisam Shanavas', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Omar Nurein', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Oscar Friesen', 'prospect', 'pipedrive_import_2025', 'Paraguay', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



