-- Batch 6 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Jim Holden', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('One Digital (Digaprint Ltd t/as)', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Colman Group', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Webflex Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Printing Centre', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Copyshop', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('PAC Graphics Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Northern Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Elephano', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('CZ Design & Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Tiger Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Leafletfrog', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Gravesham Borough Council', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('John Brailsford Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Clearprints2011', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bowford Binding', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Animate Design', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Richardson Printing', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Colourgraphic Arts Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Hop Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Plus Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mta digital', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Company Cards Ltd.', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('West Design Products', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Minuteman Press Chesterfield', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Denham Printing Co Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Regency Printers Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('DE VOYLE LITHO', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Pendle Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Elm UK Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bectech', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('First Paige Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Flyer Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Eco Colour print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('B Bless 7 Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Deanson Wilkes (Forms & Systems) Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Darley', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('KUTMASTERZ ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Wordprint Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Imagink', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Birmingham City University', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Krazy Kopy', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Russell Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Row Type', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Proteus Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ginger Design & Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Russellipm.com', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Colourpoint  Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Screen Scene Uk Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('City of Wolverhampton Council', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Binary Professionals Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('University Of Derby School Of Art & Desi', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Rustic Fox', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Odey Publications', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ink Doctor Associates', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Stratford Academy', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Trinity Framing Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Copy Right Print Services Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Blackwell Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Axminster Printing Co Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printers Mart Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('KB Consulting', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('A.L. Mailing Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print Plan litho', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The National Artificial Eye Service', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Rbkc', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mortons Media Group Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Newmont', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cre8mate', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Back To Basics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Skyward Graphics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Beck Print Finishers Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print Project', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Centriforce Products Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Leicester City Council', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Rainbow Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Fortnum & Mason PLC', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('ThreeBees', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Granthams Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Stone Melon', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Copy and Print Centre', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Hsbc', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Noel Tatt', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Kanda Print Midlands Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Print Shed Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Document Despatch Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Laser Signs Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Masters Golf', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Seed Card Company', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('R & R Printers Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Barnwell Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Linda Wood Designs', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Garthwest Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mommy Knows Best', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Sharp Printing Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Card Baste Designs', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('LDK Print & Embroidery', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Chameleon Copy and Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('ReclaimTaxUK', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Britannia Labels Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



