-- Batch 47 of 47
INSERT INTO companies (company_name, type, lead_status, lead_score, country, source, notes, status)
SELECT * FROM (VALUES
  ('Metro Taxis', 'prospect', 'hot', 50, 'England', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Westfield Europe S.r.l.', 'prospect', 'hot', 50, 'Moldova', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Sean Gallery', 'prospect', 'hot', 50, NULL, 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Cramcharts', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Mohit Kumar', 'prospect', 'hot', 50, 'India', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Portal Printing House', 'prospect', 'hot', 50, 'Serbia', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('The School Network', 'prospect', 'hot', 50, 'England', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Printing Feys', 'prospect', 'hot', 50, 'Belgium', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Jasmine Paperie', 'prospect', 'hot', 50, 'Canada', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('KNIVES OUT RECORDS', 'prospect', 'hot', 50, 'France', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Graphic Technology', 'prospect', 'hot', 50, 'UAE', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Ivan Obradovic', 'prospect', 'hot', 50, 'Serbia', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Store Impresiones', 'prospect', 'hot', 50, 'Chile', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Metro Presort Inc.', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('NBES Ltd', 'prospect', 'hot', 50, 'YO26 8LE', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Hung Nguyen', 'prospect', 'hot', 50, NULL, 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Marpimar Edizioni', 'prospect', 'hot', 50, 'Italy', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Paragon Bretagne Routing (France)', 'prospect', 'hot', 50, 'France', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Amol Kamble', 'prospect', 'hot', 50, 'Maharastra 401209 India', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Boston Moores', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Creative Visions', 'prospect', 'hot', 50, 'Australia', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Amy Popoff', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Jakson', 'prospect', 'hot', 50, NULL, 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Digi Print', 'prospect', 'hot', 50, 'Zambia', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Josh Rosen', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Robert Bloecker', 'prospect', 'hot', 50, NULL, 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Joram Njuguna', 'prospect', 'hot', 50, 'Kenya', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Dragan Tomic', 'prospect', 'hot', 50, 'Croatia', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Mega International', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Gabe Lopez', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('COPYPRINT (MALAYSIA)', 'prospect', 'hot', 50, 'Malaysia', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Sabri Graphco', 'prospect', 'hot', 50, 'Jordan', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Desalvo', 'prospect', 'hot', 50, 'Argentina', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Media AP', 'prospect', 'hot', 50, 'Poland', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Poor Richard''s Press', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('General Print Materials Limited', 'prospect', 'hot', 50, 'England', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('De Bink Opmeer', 'prospect', 'hot', 50, 'Netherlands', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Thomas Printworks', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Gilbert Salcedo', 'prospect', 'hot', 50, 'Philippines', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('PostNet Westmont IL', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Southern Charm Printing, LLC', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('J.Abisek', 'prospect', 'hot', 50, 'India', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Renan Salgues', 'prospect', 'hot', 50, NULL, 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Zeeshan Khatri', 'prospect', 'hot', 50, NULL, 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Advice Printing Solution', 'prospect', 'hot', 50, 'India', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('1st Print', 'prospect', 'hot', 50, 'India', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('VICTORI PRINT LLC', 'prospect', 'hot', 50, 'Ukraine', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Print Tech', 'prospect', 'hot', 50, 'USA', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Colour Monster', 'prospect', 'hot', 50, 'GY2 4WX', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect'),
  ('Novus Print (Pty) Ltd', 'prospect', 'hot', 50, 'South Africa', 'pipedrive_import_2025', 'Owner: Steve Humphreys', 'prospect')
) AS v(company_name, type, lead_status, lead_score, country, source, notes, status)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);
