-- Batch 18 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('bvba Van Daele', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('By Wind AB (Link�ping)', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('C A Andersson & Co (CA Andersson & Co)', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('C&A Finishing Ltd', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('C/o Law Revision Commission', 'prospect', 'pipedrive_import_2025', 'Trinidad', 'active', 'Steve Humphreys'),
  ('Cadann Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Cads Impresores', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Br�derna Hansson H-Tryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('CAE', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Call Print', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Canon Italy', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Canon', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('CAPE', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Capitol Printers Ltd', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('Card Gallery', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Brukerstyrt senter M�re og Romsdal (BSS)', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Card Palace', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Cardtech AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Careprint', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Caribbean Print Technologies', 'prospect', 'pipedrive_import_2025', 'Trinidad', 'active', 'Steve Humphreys'),
  ('Caritas Vitania', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', 'Steve Humphreys'),
  ('Carlosgraphy', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Carlssons Tryckeri', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Caspersens Trykkeri AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Cassochrome', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('BSS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Catch Publishing', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('CB Forms', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('CC', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('CCET', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('CDC Printers PVT Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('CCL Puerto Rico', 'prospect', 'pipedrive_import_2025', 'Puerto Rico', 'active', 'Steve Humphreys'),
  ('Ceenia Multimedia', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('CELA Grafiska AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Bulls Graphics AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Central Press Bray Ltd', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Central Printing Press plc', 'prospect', 'pipedrive_import_2025', 'Ethiopia', 'active', 'Steve Humphreys'),
  ('Central Statistics Office', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Centrograf', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Century Fine Arts', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Century Printing Press L.L.C.', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Century Paper & Board Mills Ltd', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Chaman Enterprises', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Cheap Photography', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Chappell Printing Ltd', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Chemaly & Chemaly', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Chitransh Group of Company''s', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('ChhajedPrintery PVT Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Chroma Digital Solutions', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('By Wind AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Chromaprint India Private Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Cicero Digital and Graphic AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Cikos Stampa', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('Cameleon Paino', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Cancan AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('CARGRAFIC', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Ceh� F�rgkopiering AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Centrumtryck Mora AB / STUART Print', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Burde F�rlags AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('CERVANGRAF', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('CHAINA ART', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Chemaly & Chemaly Printing', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Chirak Printing', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('ChirakPrinting', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Cicero Printing', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('CIMAX', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Cisburo', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('City Tryck i Karlstad AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Cite Scolaire Baggio', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('City Plus Oy Product', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Classic Business Centre', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Cityprint ltd', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('City Walk', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Classic Cards', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Classic Envelopes W.L.L.', 'prospect', 'pipedrive_import_2025', 'Kingdom of Bahrain', 'active', 'Steve Humphreys'),
  ('Classic Print', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Cisburo ltd (Nigeria)', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Cliff Designs', 'prospect', 'pipedrive_import_2025', 'Barbados', 'active', 'Steve Humphreys'),
  ('Clear Way', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Clinix', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Color Dots', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('CMJ Print', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Color Plus Terrassa', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('City Digital Tryck i Helsingborg AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('COLOR PLUS TERRASSA SCP', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Colorset edition', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('Colortone Process Pvt. Ltd.', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('ColorShow', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Colour Concepts', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Colour Harmony Co. Ltd.', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Colourgram', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('Colours Private Ltd', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('ColorMaster Norge', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Compel', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Comptoir Beninois de papiers', 'prospect', 'pipedrive_import_2025', 'Benin', 'active', 'Steve Humphreys'),
  ('Compugraphic Forms Sdn Bhd', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('COMTRADE SYSTEM INTEGRATION DOO', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('Comunicaci�n Visual', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Comunica2sac.com', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Conadex', 'prospect', 'pipedrive_import_2025', 'Dominican Republic', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



