-- Batch 40 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('V�ster�skopia AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Vdesign', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Vestby Grafiske AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Visitkort-Specialisten Norens', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Visittkort Norge AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('VISUELLA', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Vizitka.com', 'prospect', 'pipedrive_import_2025', 'Ukraine', 'active', 'Steve Humphreys'),
  ('VK Printing Vetlanda', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('VK Tryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('VJ''S rubberstamps', 'prospect', 'pipedrive_import_2025', 'Dominican Republic', 'active', 'Steve Humphreys'),
  ('Volkov SP', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('vSirius Printing', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Vp book binding and offset', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('VST Press', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Vuoliainen Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Vyoma Graphics', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('W Print Sweden AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Waked Emballage', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Walsh Graphic Design', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Waraqiah P. Press', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Web Spider (Pvt) Ltd', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Waves Press', 'prospect', 'pipedrive_import_2025', 'Kuwait', 'active', 'Steve Humphreys'),
  ('Web Composition', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Waves Branding Ltd.', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('Wecom Paris', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Weera Industries (PVT) Ltd', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Well-Known Printing Equipment Co', 'prospect', 'pipedrive_import_2025', 'Taiwan', 'active', 'Steve Humphreys'),
  ('Wera AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('West Print', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('V-Tab Norrahammar AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Westpak Loading/Unloading', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Westrock-MPS', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('What A Print Partner Pite� AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('whatstheplan.ie', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('White Shell Imaging', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('White Hospitality', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Wiking Offset & Digital Tryck Malmberg A', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Williams Printing Service', 'prospect', 'pipedrive_import_2025', 'Trinidad', 'active', 'Steve Humphreys'),
  ('Wiking Reklam AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Williamssons Offsettryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('W�hlin Produktion AB / Happify (Oskarsha', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Wisa Grafisk as', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Wipnpro', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Winston Design', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('World CSR Day', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('WOKE DIGITAL LASER PRINTING', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Worldprint', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Wrenco Limited', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Worldwide Online Printng', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Xel Creations', 'prospect', 'pipedrive_import_2025', 'Zambia', 'active', 'Steve Humphreys'),
  ('xerox', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', 'Steve Humphreys'),
  ('W�hlin Produktion AB / Happify (Stockhol', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Xmpie', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('X-O Graf Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Xpress Impresores Sa De Cv', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Xpressprint', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Xpressprint AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('X-Print Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('XXL PRINTING SOLUTIONS', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Xtreme Signs & Graphics Ltd', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('XZONE', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Wennbergs trykkeri AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Yara Printing Services', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Yash print & pack', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Yashashree Network', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Yelda', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('Yediz Ofset', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Yello Digital AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Yellow Dog Digital Press', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Yin printing', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Yogakshi Arts & Computers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ystad-Tryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Yunfan', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Zaabeel Advertising', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Wexoprint', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Zafiris Offset Printers', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('Zaitouna for Printing', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Zaman Printing and Packaging', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Zaware', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Zaware Creative', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Zaza Print', 'prospect', 'pipedrive_import_2025', 'Ukraine', 'active', 'Steve Humphreys'),
  ('Wikstr�ms Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Worums Trykkeri AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('WPE Sweden AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('X-Gloo Norway', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Xid�', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('XL Tryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('XP Consulting Pty Ltd', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Yakobs Ram & Reklam', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Zeejprint', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Zhongshan Huatong Packaging Indus', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Zion graphics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Zigijoy Design Limited', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Zomrrod', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('Zprint', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Abduljalil Alabbasi', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', 'Steve Humphreys'),
  ('Abhay Patil', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Acher', 'prospect', 'pipedrive_import_2025', 'Congo', 'active', 'Steve Humphreys'),
  ('Zuku Prints', 'prospect', 'pipedrive_import_2025', 'Zambia', 'active', 'Steve Humphreys'),
  ('Adesh Satpute', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



