-- Batch 27 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('KJ Estonian Partners', 'prospect', 'pipedrive_import_2025', 'Estonia', 'active', 'Steve Humphreys'),
  ('Kjells Tryckeri', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('KM Digital', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Klubbtryck', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('KM Kapell AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('KMJ', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('KNITCITY GRAPHICS PVT LTD', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kolm L�vi Tootmine O�', 'prospect', 'pipedrive_import_2025', 'Estonia', 'active', 'Steve Humphreys'),
  ('Komigraphic', 'prospect', 'pipedrive_import_2025', 'Albania', 'active', 'Steve Humphreys'),
  ('Konica Minolta', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Konica Minolta Croatia', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Konica Minolta Russia', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('Konos Press', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('Konstn�rernas Kollektivverkstad i G�tebo', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Korea Uni Com Co Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Kot', 'prospect', 'pipedrive_import_2025', 'Albania', 'active', 'Steve Humphreys'),
  ('KPJ PRINTING SERVICES, INC.', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Krishna Paper Works', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Koopia Niini & Rauam', 'prospect', 'pipedrive_import_2025', 'Estonia', 'active', 'Steve Humphreys'),
  ('Krobia Service', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('KT Printing', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('KSC Engineering', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Kung�lvs SkyltMakeri', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Kvernberget Print & Advertising AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kvernberget Print & Reklame', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('L&A Nicolaou', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('L.I.P. sas', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Kirjapaino Painosalama', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('L.R. SISTEMI S.R.L', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('La Ceiba Honduras', 'prospect', 'pipedrive_import_2025', 'Honduras', 'active', 'Steve Humphreys'),
  ('La Solution Bureautique', 'prospect', 'pipedrive_import_2025', 'Djibouti', 'active', 'Steve Humphreys'),
  ('La Tiragerie BuroCAD', 'prospect', 'pipedrive_import_2025', 'Mali', 'active', 'Steve Humphreys'),
  ('Laehui Shop', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Landgraphic', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Lahden V�riasemointi Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('LANAREPRO GmbH', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Lando Heita Investment cc', 'prospect', 'pipedrive_import_2025', 'Namibia', 'active', 'Steve Humphreys'),
  ('Lantz Cards Direct', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Lapin Mainospalvelu Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Large Format Print AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Larsson Offsettryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Laser Co', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('LaserMedia Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Le Topical', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Layer Recipe', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Leaflet Express', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Leerdam Druk bv', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Klesprofil', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('LEGRAND FACONNAGE', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Leaflet Express / Sprint The Printer', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Lehtiliiteri', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Klisterdekor AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('LABEL ART FACTORY', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Kraft', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kph Trycksaksbolaget AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Kronemerker', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kortshop AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kopirett H3 ikt as', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kopiopaja', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Kopiecenter BWA AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Konsultkopia AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Kopianstalten A/S', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kontikett', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Konsis', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('KML FAGERNES PRINT & ADVERTISING', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('km8650', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', 'Steve Humphreys'),
  ('Kilpi- Ja Opastetalo Ra-Ri Kilpi Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Leo Paper Bags Manufacturing(1982) Ltd', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', 'Steve Humphreys'),
  ('Lehtitehdas', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Lenanders Grafiska AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Leo Print', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('Les Editions Europ�ennes', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Letece', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Letter and Form Pty Ltd', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Leturstofan', 'prospect', 'pipedrive_import_2025', 'Iceland', 'active', 'Steve Humphreys'),
  ('LH Tryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Librix Print O�', 'prospect', 'pipedrive_import_2025', 'Estonia', 'active', 'Steve Humphreys'),
  ('Licon', 'prospect', 'pipedrive_import_2025', 'Ukraine', 'active', 'Steve Humphreys'),
  ('Lidbergs Grafiska AB Tryckeri Sk�ne och', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Lier graphic AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Lifegate Publishing Co. Ltd.', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Light and Color Management Consultancy', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Light House Print', 'prospect', 'pipedrive_import_2025', 'Zimbabwe', 'active', 'Steve Humphreys'),
  ('Linotype', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Lithocromo', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Lithographie L''ancre', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('Litografen i Vinsl�v AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('LEQUE GR�FICO LDA', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('LITOGRAFIA DE OCCIDENTE', 'prospect', 'pipedrive_import_2025', 'GUATEMALA', 'active', 'Steve Humphreys'),
  ('Litografia del Sur SAC', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Litorapid Media AB / By Wind', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('LITOTEC', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('lm graphic', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('LKT digital AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Lotus ent', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Lotus Printing & Events', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('LS Card Ltd', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('LS Offset AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('LTAB Link�pings Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Lubanda Print & Branding', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



