-- Batch 34 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Rajams', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Rally Inc', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Rakyat', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Quick Quality Print', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Ramco Group Ltd', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('Ramin Imprimerie', 'prospect', 'pipedrive_import_2025', 'Reunion', 'active', 'Steve Humphreys'),
  ('Rangoli Prints', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Rangoli Studio', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ranjas Printing Press', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('rapidbox.com', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Rapidkopia I Norrk�ping AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('RARE Darbnica', 'prospect', 'pipedrive_import_2025', 'Latvia', 'active', 'Steve Humphreys'),
  ('Rauman Painopiste Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Radix Designs', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ravi Raja Offset Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Rawee', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('RB PRINT', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Recyl Graphics', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Redak', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Regional Press', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Raidy Emirates Printing Group', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Rehmath Villa', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Reimari Printing Works', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('REJ PRINT AND STATIONERY', 'prospect', 'pipedrive_import_2025', 'Tanzania', 'active', 'Steve Humphreys'),
  ('RELIABLE PIPES & TUBES LTD.', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Renessanse Media AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Reparaciones Navales y Terrestres Sal', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Repro Graf', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Repro India Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Reprografika', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Resultatreklam AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Reprographic System & Supplies', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Reprografika d.o.o.', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Reyno Publishing', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('RGB Image', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Right Click Print Services', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('RightWrite Enterprises', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Riot Books', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('rishikul prakashan', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Risteen Kirjapaino Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Raidy Lebanon', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Riviera', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('RAIDY LEBANON  Printing Group', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Raision Mainosteippaus', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Randaberg Trykk AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Rauman Painopiste Oy / Kutsukortit', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Reklame-huset.no', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Reklamhuset Printia AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Ressurs AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Revotech Empresa', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('rg tryck', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Ring�ns Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Rk Grafisk AS / Grafix Ferdiggj�ring AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('RNDr. Karael Martycak', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', 'Steve Humphreys'),
  ('RN Digital Print', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Roeyah adv.', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Rob Pollock Photography and Framing cc', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Rohan Press', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Romande Energie', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('Rom Media', 'prospect', 'pipedrive_import_2025', 'Tanzania', 'active', 'Steve Humphreys'),
  ('Roop Printig Press', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Roopaa Creatives', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ropredave Books Supply and Gen. Mdse.', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Rosemood', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Roseprint Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Rosalnes Impresores', 'prospect', 'pipedrive_import_2025', 'Bolivia', 'active', 'Steve Humphreys'),
  ('Rosieh', 'prospect', 'pipedrive_import_2025', 'Haiti', 'active', 'Steve Humphreys'),
  ('Rolf Ottesen AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Rotografika d.o.o.', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('Royal graphics', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Royal Graphics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Royal Printing Press', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('RPKBD', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('RPS', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ruad United', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Rubio Valentines', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Romanya Valls', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Rumi Jumi Enterprise', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('S Prints', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('S.K.COMPUTERS', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('S.N. Offset Press', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('SAA Advertising LLC', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Sabri Group of Companies', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Sacerdoti Empresa Grafica', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', 'Steve Humphreys'),
  ('Sads', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('S�thren & Wraamann AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('SAF Printers', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Safepack', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Safir', 'prospect', 'pipedrive_import_2025', 'Iran', 'active', 'Steve Humphreys'),
  ('Sagacom', 'prospect', 'pipedrive_import_2025', 'Bolivia', 'active', 'Steve Humphreys'),
  ('Sagitario', 'prospect', 'pipedrive_import_2025', 'Bolivia', 'active', 'Steve Humphreys'),
  ('Sahajanad Graphics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Sahyadri Info Solutions', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Sai Offset Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Sai Sakti Printer', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Saiamrutha Creations', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Sakartvelos Matsne', 'prospect', 'pipedrive_import_2025', 'Georgia', 'active', 'Steve Humphreys'),
  ('Saipress Prints', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Salma chikhrouhou', 'prospect', 'pipedrive_import_2025', 'Tunisia', 'active', 'Steve Humphreys'),
  ('Same Day Print', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



