-- Batch 14 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('&soWalter (usw.) risography', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('2A G�rsel ��z�mler', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('8392', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('1st Point Digisep', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('123PRINTSERVICES', 'prospect', 'pipedrive_import_2025', 'Ivory Coast', 'active', 'Steve Humphreys'),
  ('2M Professional Printing', 'prospect', 'pipedrive_import_2025', 'Puerto Rico', 'active', 'Steve Humphreys'),
  ('07 Media AS / Aksell', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('3P-Post Print Provider', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('37BMEPK9407N1ZI', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('A - Sign', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('A & M Printing', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('A C Comm Imprimerie', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('A1 Reklame AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('A&S Gr�fica y Representaciones E.I.R.L.', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('A4 Tulosta Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Aarish enterprises', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('AB Grafisk Stil', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('AB Kontorsrutin', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('AB Sparven & Co', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('ABAco', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Abc bookstore', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('ABC-Tryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('ABDonald Ltd', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Abdoul khan', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', 'Steve Humphreys'),
  ('3D REKLAM', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Abdul-Aziz M. Al-Ghamdi Est.', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('�bergs Tryckeri', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Abirami audio recording pvt ltd', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('53 Dots Printing', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Aboupointu2013', 'prospect', 'pipedrive_import_2025', 'Chad', 'active', 'Steve Humphreys'),
  ('Abhijit Enterprises', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('abprintanddesign', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Abprint & Design', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Absolut Trykk', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Absolute', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Absolute Graphics Print & Web Solutions', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Abstract', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('ABT Group', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('Acacia Factory', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('ACAD�MICA,  LDA.', 'prospect', 'pipedrive_import_2025', 'Mozambique', 'active', 'Steve Humphreys'),
  ('ACBMV', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Ace Data', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ace Digital Revolution Co., Ltd.', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('ACT Card', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Addsky Ltd', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Adgifts (India) Pvt. Ltd.', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Adkit', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('AdishKthioffset printer', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Aditya Offset', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ad-Mag Pty Ltd', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('ADS', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('ADOSA', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('ADS Australia', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('AdvPromotions LTD', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', 'Steve Humphreys'),
  ('Advait Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Adstime', 'prospect', 'pipedrive_import_2025', 'Georgia', 'active', 'Steve Humphreys'),
  ('Afrique Orient', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Agentia De Print', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('AGM Imprimerie', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Ahmed Salih', 'prospect', 'pipedrive_import_2025', 'Sudan', 'active', 'Steve Humphreys'),
  ('Airlink Intl. Private Ltd.', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('AirMed Systems', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('AIT Oslo AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Ajandci', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Aj Creation', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('AJAY PRINTERS', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Akgul Ofset & Matbaacilik', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ajooba', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Akarsha Printers', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Akhil Enterprises', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Akitiara', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('Akshar International Inc', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Akshar offset', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Akshar Reprographs', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Akshaya Mudrana', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Aksharchitra', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('AB S�dermalms Snabbkopiering', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Akyl-D', 'prospect', 'pipedrive_import_2025', 'Kazakhstan', 'active', 'Steve Humphreys'),
  ('AB T Opto', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('AB Tidaholms Grafiska', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('AB Wasatryckeriet', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Accidens', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Acello Print AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Acon Press', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', 'Steve Humphreys'),
  ('Adall Grafiska AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Advantex', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Advertising and Graphic Kiruna AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('AG Reklame', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('AHM', 'prospect', 'pipedrive_import_2025', 'Madagascar', 'active', 'Steve Humphreys'),
  ('AIT Grafisk (formerly Bjerch Trykkeri??)', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('AJ E-print AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Akaan Silkkipaino Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Aktiv Reklame AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Al Ameera Printing Press', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Al Barakeh Printing Press', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('Al Ebtekar', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Al Ain National Printing', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Al Bushra', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Al Azzaz Computer Forms', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Al Furqan Book Shop l.l.c', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



