-- Batch 43 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Padraig Parker', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Pamela Anne Yasas', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Patrick', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Paul Ryder', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Paulo Alexandre', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Pavel Dojacek', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', 'Steve Humphreys'),
  ('Pedro Alves', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Pedro Pereira', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Pere Boada', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Peter Karundeng', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Piotr Piotr', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Peter Synnott', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Praga', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Prashant Rajendra Wani', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Quamar Tahseen', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Rainer', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ramesh Vr', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Rapolas', 'prospect', 'pipedrive_import_2025', 'Lithuania', 'active', 'Steve Humphreys'),
  ('Rajesh Khatwani', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Raymond Chingwaru', 'prospect', 'pipedrive_import_2025', 'Zimbabwe', 'active', 'Steve Humphreys'),
  ('Reb Austria', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Ricard Pijoan', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Remzi', 'prospect', 'pipedrive_import_2025', 'turkey', 'active', 'Steve Humphreys'),
  ('Richard Pinto', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Rizwan Ali', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Ricardo', 'prospect', 'pipedrive_import_2025', 'Reunion', 'active', 'Steve Humphreys'),
  ('Roger', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', 'Steve Humphreys'),
  ('Rohit kumar', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Romo Puharic', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Ronny', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ruben Mamo', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Safiya Darius', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Sahebe Alam', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Samad Monsoor', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', 'Steve Humphreys'),
  ('Samir Aghallouch', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Sami', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Salman Sadiq', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('Sandra Omeje', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Samson', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Samual Sene', 'prospect', 'pipedrive_import_2025', 'Papua New Guinea', 'active', 'Steve Humphreys'),
  ('Satya', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Sayed Haroun Abdelkarim', 'prospect', 'pipedrive_import_2025', 'Sudan', 'active', 'Steve Humphreys'),
  ('Serekan Karadede', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Sergio Ballester', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Sergio Mu�oz Lopez', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Sina Youzbashi', 'prospect', 'pipedrive_import_2025', 'Iran', 'active', 'Steve Humphreys'),
  ('Sir', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Slah Djema�', 'prospect', 'pipedrive_import_2025', 'Tunisia', 'active', 'Steve Humphreys'),
  ('Soraisham Sanjila Chanu', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Sunil Jain', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Subash Babu', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Sushanta Kumar Jena', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Suraj Gadage', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Temu', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Teresa Branch', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Thomas Beenen', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Thomas van der Lubbe', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Tony Akanwa', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Tony Hunter', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Utam', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Uwe Lehmann', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Vanessa Fernandes', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Vedran Crnkovic', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Vijay Kumar', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Victor Mbiya', 'prospect', 'pipedrive_import_2025', 'Congo', 'active', 'Steve Humphreys'),
  ('Viswanathan', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Viliam Tomascik', 'prospect', 'pipedrive_import_2025', 'Slovakia', 'active', 'Steve Humphreys'),
  ('Vitor Abreu Assis', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Vivek Saboo', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Vivek Vatve', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Vladislav Vishnevskyy', 'prospect', 'pipedrive_import_2025', 'Ukraine', 'active', 'Steve Humphreys'),
  ('Whitney Mamo', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Xishood', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('William Ordu�a', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Winnie Obaga', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('Zdravko Velinov', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Yongjun', 'prospect', 'pipedrive_import_2025', 'South Korea', 'active', 'Steve Humphreys'),
  ('Zo Andriamifidisoa', 'prospect', 'pipedrive_import_2025', 'Madagascar', 'active', 'Steve Humphreys'),
  ('Yannick Tawali', 'prospect', 'pipedrive_import_2025', 'Cameroon', 'active', 'Steve Humphreys'),
  ('Jamia Printing Press', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Editora Damatele', 'prospect', 'pipedrive_import_2025', 'Dominican Republic', 'active', 'Steve Humphreys'),
  ('Paceprint', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Japak', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('National Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jorge Chipuli', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('EURODISTECH SARL.', 'prospect', 'pipedrive_import_2025', 'Luxembourg', 'active', 'Steve Humphreys'),
  ('Aimpresores', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', 'Steve Humphreys'),
  ('Elanders Hungary Kft.', 'prospect', 'pipedrive_import_2025', '8999 Hungary', 'active', 'Steve Humphreys'),
  ('Andrew Whitson', 'prospect', 'pipedrive_import_2025', 'Northern Ireland', 'active', 'Steve Humphreys'),
  ('Reflex Graphic', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('Anand MC', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Highline Office Technology', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Anand Graphics', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Smurfit Westrock', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Vusi Masombuka', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('ImageTech Solutions', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('CHEVILLON IMPRIMEUR', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Over Copy', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Shree Maa folding works', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Acrialbi Acrilicos e Decorações,Lda', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



