-- Batch 38 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('The Print Company', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Taberg Media Group I V�xj�', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('The Print Experts Ltd', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('The Printing World', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('The Safire Offset Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('The Print House', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('The Warehouse', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('The SHINE GrafiX', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('The Wedding Bell', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('THEGIOITHECAO.VN', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('Thelma Printing', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Theodorou printing co ltd', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('Theopress ltd', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('ThienThuyCo.,Ltd', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('Think And Design', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('TADAVOM CO', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Teko Print & Copy AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Telegrambolaget i Karlstad AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Teto Grafiske AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Thaiba printing presS', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('The Irish Times Print Facility', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Thunder Print Sdn Bhd', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('Tigran Mets Publishing House', 'prospect', 'pipedrive_import_2025', 'Armenia', 'active', 'Steve Humphreys'),
  ('Tik Communications', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Tholasi Prints India Pvt. Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Tidtryck in Uppsala', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Thumbprints Ltd', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('Timeless Design', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('TIFT d.o.o.', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Time Pass Cyber', 'prospect', 'pipedrive_import_2025', 'Nepal', 'active', 'Steve Humphreys'),
  ('TIMS Limited', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('TINDE Design & Trykk', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Tintanegra', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Tinta L.T.D.', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Tiparesc Amintiri SRL', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Tipografia Creativamente', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Tirupathy Enterprise', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Tirupati Enterprise', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Tisk Print', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Tingsryds Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('tiskhorak a.s', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', 'Steve Humphreys'),
  ('Tlaciaren', 'prospect', 'pipedrive_import_2025', 'Slovakia', 'active', 'Steve Humphreys'),
  ('TME', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Tm Engg Corp', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('T-Man Grafiska Mediakontoret i Norrk�pin', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('TKJ International Ltd', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('tms enterprices', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Toba Art Press', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Toil and Tinker', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Tokoglu Ofset', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Topcom Printers', 'prospect', 'pipedrive_import_2025', 'Tanzania', 'active', 'Steve Humphreys'),
  ('Toiprint Ltd / Digital Printing / Offset', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('topkartka', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Total Digital Solutions', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Total Trykk AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Tott-Print Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Totem', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('TPS PRINTING', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', 'Steve Humphreys'),
  ('TPPS World (HK) Ltd', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('TR Graphics', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Tradinco', 'prospect', 'pipedrive_import_2025', 'Uruguay', 'active', 'Steve Humphreys'),
  ('Tradidi', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Top Printers', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', 'Steve Humphreys'),
  ('Trangphat', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('TR-DESIGN', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', 'Steve Humphreys'),
  ('Trajanus storitve d.o.o.', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Trident Creative Studio', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Trilines Printing House', 'prospect', 'pipedrive_import_2025', 'Latvia', 'active', 'Steve Humphreys'),
  ('Trinidad Systems Ltd', 'prospect', 'pipedrive_import_2025', 'Trinidad WI', 'active', 'Steve Humphreys'),
  ('Trio Tryck AB � en del av Prinfo Welins', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('TRIPRINT CORPORATION', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Triq L-Iskultur', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Triumph Printers', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Trojan Print', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Tru Creations FZE', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Trueprintings & Designs', 'prospect', 'pipedrive_import_2025', 'Suriname', 'active', 'Steve Humphreys'),
  ('Tryck i Norrbotten AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckcentrum i Blekinge AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeri City i Ume� AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckcentrum i Blekinge AB (S�lvesborg)', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Trade Digital Print', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Tryckeri Stockholm / c/o Flighton AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeri JustNu Malm�', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Trydells Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckkedjan AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('TRZ International', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Tuna Matbaacilik San. Ve Tic. A.S.', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Tuk Tuk Charity', 'prospect', 'pipedrive_import_2025', 'Cambodia', 'active', 'Steve Humphreys'),
  ('Tungipara Electric Manufacturer Company', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('TRS Tryck Reklam Skylt', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryck & Skyltforum AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckakuten Sverige AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeri JustNu G�teborg', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeri JustNu H�gersten', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeri JustNu Karlstad', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeri JustNu Stockholm', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeri JustNu Trollh�ttan', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeri JustNu V�ster�s', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('tryckeri1.com', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tryckeriet i �lmhult', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



