-- Batch 30 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Nem Data', 'prospect', 'pipedrive_import_2025', 'Denmark', 'active', 'Steve Humphreys'),
  ('NeomashLtd', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', 'Steve Humphreys'),
  ('New Flash Media', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', 'Steve Humphreys'),
  ('New Generation', 'prospect', 'pipedrive_import_2025', 'Mali', 'active', 'Steve Humphreys'),
  ('NEW GRACE DIGITAL', 'prospect', 'pipedrive_import_2025', 'Congo', 'active', 'Steve Humphreys'),
  ('New Lalith Printers', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Moser Druck', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', 'Steve Humphreys'),
  ('New Metals Co.', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('New Life Literature', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('New Numchuan Printing Co., Ltd.', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('newcam systems (1990) pte ltd', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Newprint Ltd', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Next Print Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Nexus Prints', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('NFI - Norwegian Formularindustri AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Multi Paino', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('MWM GROUP AB / Print 365', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Nabeel Printing', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('N�rtryck Alltrycksaker I Norrk�ping', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Nilssons Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Niche Reprographics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Nguyen Thien Company', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('NIHON SEIZUKI KOGYO CO., LTD', 'prospect', 'pipedrive_import_2025', 'Japan', 'active', 'Steve Humphreys'),
  ('Nilz & Otto Graphic AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Ningeri', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Nir tal print', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Nkitnto enterprise co ltd', 'prospect', 'pipedrive_import_2025', 'Tanzania', 'active', 'Steve Humphreys'),
  ('Nobel Art', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', 'Steve Humphreys'),
  ('Noble Printing Press', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('NORAMI s.r.o.', 'prospect', 'pipedrive_import_2025', 'Slovakia', 'active', 'Steve Humphreys'),
  ('Nordic 3D', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Nord Sud Impression', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Norsk Etikett AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Norsk Filmtrykk AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Nor-trykk Narvik AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Northern Star Press', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Nilz & Otto Grafisk AS avd. Storformat', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Notre Dame Priory', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Nova-Print Stavanger AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Novaya Poligrafia', 'prospect', 'pipedrive_import_2025', 'Kyrgyzstan', 'active', 'Steve Humphreys'),
  ('NRA Repro AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Ntong', 'prospect', 'pipedrive_import_2025', 'Cameroon', 'active', 'Steve Humphreys'),
  ('Nu Print Ltd', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', 'Steve Humphreys'),
  ('Nuevo Color Artes Graficas', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', 'Steve Humphreys'),
  ('Nilz AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('N�meros y Marquillas SAS', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', 'Steve Humphreys'),
  ('NUSRA printers Pvt ltd', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Nuzum Al EElan Digital Printing Jeddah', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('NYC Printing Press', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('oai impression', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Octobox', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Nordic Print AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Offbeat Concepts Design Studio', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('OFFSET ABAD C.A', 'prospect', 'pipedrive_import_2025', 'ECUADOR', 'active', 'Steve Humphreys'),
  ('OFFSET ABAD', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Offset Press Ltd', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Offset Printers', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Offset Ulonen Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Offsetdruck Grauwiller Partner AG', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('Nordvalls Etikett AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('OffsetKolmio Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Offsetpaino Westman Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Ofset aco', 'prospect', 'pipedrive_import_2025', 'Macedonia', 'active', 'Steve Humphreys'),
  ('Ohanna Holdings Limited', 'prospect', 'pipedrive_import_2025', 'Trinidad & Tobago', 'active', 'Steve Humphreys'),
  ('Om Art Print', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('om offset', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Oman Printers and Stationers Ltd', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('Omega Trykk AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Omniva', 'prospect', 'pipedrive_import_2025', 'Estonia', 'active', 'Steve Humphreys'),
  ('Norrbotten Grafisk Design', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('OMsport.no | Masita Sportswear Norge', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('�m�r Printing & Packaging', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Online Prints', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('OnnoRokom Software Ltd.', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('Onsign i Gnosj� AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Open2view Print Services South Australia', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Ontime llc', 'prospect', 'pipedrive_import_2025', 'Mongolia', 'active', 'Steve Humphreys'),
  ('Optimum', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('NorrDeal', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Orange Offset', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Oriental Press Dubai', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Oriental Printing press & Stationery', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('Origin Binding works', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Original Tryckeri i Ume�', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Ornate Communications', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Orrvee Industries', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('ORTINDO DIGITAL PRINT', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Norwegian Signs Engraving AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('OS Printing Centre', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Osaka Sealing Printing Co. Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('NS Schneider Media', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('NTS Profil & Reklam', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Numedal Trykkservice', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('NYE SIDER AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Nygrens Ljuskopia AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Nyman & Jonsson AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Obelisk trykk AS / Etiketter As', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Office Copy Center i �sterg�tland AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Onlinepaino', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Ordgruppen ek f�r', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



