-- Batch 37 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Stormlink Grou', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('STUART Print', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Studio 10 Design & Print', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Studio Graphics', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Studio Kiki', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Studio Texo', 'prospect', 'pipedrive_import_2025', 'Slovakia', 'active', 'Steve Humphreys'),
  ('Spiik Up AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Subligrafic', 'prospect', 'pipedrive_import_2025', 'Venezuela', 'active', 'Steve Humphreys'),
  ('studip/drukkerij PK84', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Sudarshan Stationery Mart', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Sudha Printers', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('SUDHA PRINTERS', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Sumitech Industrial Supplies & Technical', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Suomen Kangaspaino Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Suomen 3D-malli Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('SUNRISE LABEL COMPANY PRIVATE LIMITED', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Supapel', 'prospect', 'pipedrive_import_2025', 'Costa Rica', 'active', 'Steve Humphreys'),
  ('Superkraft', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Suprabhat', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Supressa Graphics PVT. Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Susanne Maria ART Design Illustration Re', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Suve Graphics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Surya chandra Industries', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Svanqvist Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Sporttiveikot Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('SR UNIQUE PRINTS', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Star Printing Company', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Stema Specialtryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Studio brandis � design och letterpress', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Studio11 Printhouse', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Sultan Printing', 'prospect', 'pipedrive_import_2025', 'Kuwait', 'active', 'Steve Humphreys'),
  ('Sundskopia Colour Center AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Suomen Laserpalvelu Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Svenska Tj�nstegruppen', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Svanstroms Repro Center AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Swami Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Swissmem', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('SweToner Reklam & Refill', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Swiat Druku', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Syriani and Sons', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Synapse', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Systematics', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Systeme Graphique', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Taitotupa', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Tacto grafico', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('T�kja�j�nustan ehf', 'prospect', 'pipedrive_import_2025', 'Iceland', 'active', 'Steve Humphreys'),
  ('Taj 51', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Sweet Printery', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tallah printing', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Talaween Advertising Agency', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Tamar SY Import & Marketing Ltd', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Tanabutr Co Ltd', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Tangen C Media', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Tanvi Creation', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Targuet SRL', 'prospect', 'pipedrive_import_2025', 'Bolivia', 'active', 'Steve Humphreys'),
  ('TaraLets Computer House', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Taberg Media Group I Gothenburg', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tauler Laminating Tech', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Taskbiz', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('TB Printsolutions AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('TC Impresores s.a.s.', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', 'Steve Humphreys'),
  ('Technico P.Press', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Techno-Savy Indusatries', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Technical Printing Press', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Taberg Media Group I J�nk�ping / Taberg', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('TECHNOPLI', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Technowin', 'prospect', 'pipedrive_import_2025', 'Ukraine', 'active', 'Steve Humphreys'),
  ('Techtronix Ltd', 'prospect', 'pipedrive_import_2025', 'Rwanda', 'active', 'Steve Humphreys'),
  ('Techtronics', 'prospect', 'pipedrive_import_2025', 'Trinidad', 'active', 'Steve Humphreys'),
  ('Tecnicromo Artes Gráficas, lda', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('T�cnicas y Proyectos Editoriales, S.A.', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Tecnica Grafica snc', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('TECNIPRINT', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Tecnoformas SA', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Tehnic NXprint', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Taberg Media Group I Halmstad', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tekkrom', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', 'Steve Humphreys'),
  ('Tekniseri Oy (Pori)', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Temple Packaging PVT Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Tellogruppen AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Tero Print Oy (Mikkeli)', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Tenaui Middle East', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Tetab Print Solutions', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Text 4U i Stockholm AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Taberg Media Group I Malm�', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Textiles S.A.', 'prospect', 'pipedrive_import_2025', 'Guatemala', 'active', 'Steve Humphreys'),
  ('Textprint AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('ThanhDat Printing CO.,LTD', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('Thabet Son Corporation', 'prospect', 'pipedrive_import_2025', 'Yemen', 'active', 'Steve Humphreys'),
  ('The African House', 'prospect', 'pipedrive_import_2025', 'Sudan', 'active', 'Steve Humphreys'),
  ('The card company', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('The Copy Centre', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('The Direct Solutions Company', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Taberg Media Group i Stockholm', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('The Lion Rock Press Limited', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', 'Steve Humphreys'),
  ('The Magic Touch Algerie', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('The Mark Communication', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('The Media Mafia', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('The morning star Multi-ventures', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('The New 4th Dimension LLC', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



