-- Batch 1 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Count Machinery Co', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Excell Color Graphics', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Jay printing', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Printlink', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Corporativo Grafico', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('GM Global Printing MATERIALS', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('A.R Hijjawi & Sons Co Ltd', 'prospect', 'pipedrive_import_2025', 'Palestine', 'active', 'Steve Humphreys'),
  ('Livonia', 'prospect', 'pipedrive_import_2025', 'Latvia', 'active', 'Steve Humphreys'),
  ('Golden line office', 'prospect', 'pipedrive_import_2025', '4159 Jeddah K.S.A', 'active', 'Steve Humphreys'),
  ('OM Vir Print O Pack', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Manjarrez', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Cezanne Printing House', 'prospect', 'pipedrive_import_2025', 'Georgia', 'active', 'Steve Humphreys'),
  ('Artron s.r.o.', 'prospect', 'pipedrive_import_2025', 'Czechia', 'active', 'Steve Humphreys'),
  ('Lodha Offset Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Raval Trading', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Print house creative design & print solutions', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('Pine Town Printers', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Maypap', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('Graforad', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Riverside Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('New Century Press', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Stella Print and Design', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('Maxi Grafica', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Grafische Afwerking Josuma', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('QuickImages', 'prospect', 'pipedrive_import_2025', 'Grand Cayman', 'active', 'Steve Humphreys'),
  ('Tipăresc amintiri', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Sun Hing Printing Holdings Ltd', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', 'Steve Humphreys'),
  ('MDVDDFUS', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Mohamed Khalil', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Anand Xerox', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Grafoprom design and print house', 'prospect', 'pipedrive_import_2025', 'North Macedonia', 'active', 'Steve Humphreys'),
  ('Dwight Williams', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('The Copy Shop', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('KEN WILKINS PRINT LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Print Expert', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PrimeTech Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PRINT DESIGN & SIGN LTD', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Seventy9 Website Design Print & Digital Marketing', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PMG Print Management', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Aura Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('HAD-PRINT', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Route 1 Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Gemini Print Group', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Jack Harris'),
  ('Print 4 Business Ltd', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('GBF Labels Print & Packaging', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Dominion Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Jack Harris'),
  ('Potts Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('OASTHOUSE MARKETING DESIGN AND PRINT LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('REDTREE PRINT SOLUTIONS LTD.', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Print-Tech Solutions Ltd', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PRINT UK LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('SLS Print Limited - London - UK', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Independent Print Industries Association', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PSL Print Management', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Gold Design Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Jack Harris'),
  ('PRE-PRINT TECHNOLOGY LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('County Print Finishers', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Bayan Group', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Rusconitechnology', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('JDC Priting Tech Sri Lanka', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('G.K. Print House Pvt. Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Fabrifolder', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', 'Steve Humphreys'),
  ('Tuicial', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Max Copy Center', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('E7 Printing', 'prospect', 'pipedrive_import_2025', 'U.A.E', 'active', 'Steve Humphreys'),
  ('Socios', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Imprensa National', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('My Prints.co.ke', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('Printech Machineries', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('PMWEB Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Graphic Arts Group | Sign & Display | Corporate Print | Promotional Merchandise | Labels', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Banner Box Print Solutions', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Wallace Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('The Print Magician', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('NAVILLUS PRINT GIFTS LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Spin Print Solutions', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Olympus Print Group Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Jack Harris'),
  ('LT Print Group', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PAPCOM Digital Print Ltd', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Duuilo Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Kruno Ivanković', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Imprimerie Papeterie du Congo', 'prospect', 'pipedrive_import_2025', 'Congo', 'active', 'Steve Humphreys'),
  ('MGX Digital', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Auckland Copy Shop', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('RedPanda', 'prospect', 'pipedrive_import_2025', 'Kazakhstan', 'active', 'Steve Humphreys'),
  ('Barbara Middleton', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('John Nixon', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Sadek Group', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('MVL Valletta Ltd', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Master Kina', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('The Mail Haus, Inc', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Kenlis Trading', 'prospect', 'pipedrive_import_2025', 'Namibia', 'active', 'Steve Humphreys'),
  ('Orchid', 'prospect', 'pipedrive_import_2025', 'Sultanate of Oman', 'active', 'Steve Humphreys'),
  ('Staffordshire Printing Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Modern Technology', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('Jose David Valle', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Seana Giles', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Gaétan Mahé Photographies', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Ricardo Chung', 'prospect', 'pipedrive_import_2025', 'Panama', 'active', 'Steve Humphreys'),
  ('Snap Campbelltown', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



