-- Batch 47 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Metro Taxis', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Westfield Europe S.r.l.', 'prospect', 'pipedrive_import_2025', 'Moldova', 'active', 'Steve Humphreys'),
  ('Sean Gallery', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Cramcharts', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Mohit Kumar', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Portal Printing House', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('The School Network', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printing Feys', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Jasmine Paperie', 'prospect', 'pipedrive_import_2025', 'Canada', 'active', 'Steve Humphreys'),
  ('KNIVES OUT RECORDS', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Graphic Technology', 'prospect', 'pipedrive_import_2025', 'UAE', 'active', 'Steve Humphreys'),
  ('Ivan Obradovic', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('Store Impresiones', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', 'Steve Humphreys'),
  ('Metro Presort Inc.', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('NBES Ltd', 'prospect', 'pipedrive_import_2025', 'YO26 8LE', 'active', 'Steve Humphreys'),
  ('Hung Nguyen', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Marpimar Edizioni', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Paragon Bretagne Routing (France)', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Amol Kamble', 'prospect', 'pipedrive_import_2025', 'Maharastra 401209 India', 'active', 'Steve Humphreys'),
  ('Boston Moores', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Creative Visions', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Amy Popoff', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Jakson', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Digi Print', 'prospect', 'pipedrive_import_2025', 'Zambia', 'active', 'Steve Humphreys'),
  ('Josh Rosen', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Robert Bloecker', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Joram Njuguna', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('Dragan Tomic', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Mega International', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Gabe Lopez', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('COPYPRINT (MALAYSIA)', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('Sabri Graphco', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('Desalvo', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', 'Steve Humphreys'),
  ('Media AP', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Poor Richard''s Press', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('General Print Materials Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('De Bink Opmeer', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Thomas Printworks', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Gilbert Salcedo', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('PostNet Westmont IL', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Southern Charm Printing, LLC', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('J.Abisek', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Renan Salgues', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Zeeshan Khatri', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Advice Printing Solution', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('1st Print', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('VICTORI PRINT LLC', 'prospect', 'pipedrive_import_2025', 'Ukraine', 'active', 'Steve Humphreys'),
  ('Print Tech', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Colour Monster', 'prospect', 'pipedrive_import_2025', 'GY2 4WX', 'active', 'Steve Humphreys'),
  ('Novus Print (Pty) Ltd', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);
