-- Batch 44 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Jra impresores', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', 'Steve Humphreys'),
  ('Clampitt Paper', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('CA Ravish Lalani', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Print-Art Services Limited', 'prospect', 'pipedrive_import_2025', 'Trinidad & Tobago', 'active', 'Steve Humphreys'),
  ('UK Leaflets Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Envelope printing Zurwerra AG', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('Lgen', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Forever After Designs', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Robert Johnson', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('''+351 21 478 3363', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Reinld Printing', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Gooseberry Creations', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ricardo Lérias', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Arteos Digital S.L.', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Servigraf', 'prospect', 'pipedrive_import_2025', 'El Salvador', 'active', 'Steve Humphreys'),
  ('Print Technique', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Suresh Yadav', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('GATE ATC', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Hubspot', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Baramee Lertananchaikul', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('EPAM', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Photo Solution', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Scirocco Limited', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Imprimerie Richard', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Industria Gráfica Cimagraf S.A.C.', 'prospect', 'pipedrive_import_2025', 'Perú', 'active', 'Steve Humphreys'),
  ('Quality Print Center', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Three Z Printing', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('INTIMUS INTERNATIONAL IBERICA S.A.U.', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Offsetdruk i media sp. z o. o.', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('RUSCONI TECHNOLOGY s.r.l.', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Kelley Create', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Pabetechnic', 'prospect', 'pipedrive_import_2025', 'Hungary', 'active', 'Steve Humphreys'),
  ('Plot Centro', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Slajd', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Data Mail, Inc.', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Ashirwad Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Raymon', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Nofal For Printing', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Taharah Shahid', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('ches28@btinternet.com', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('info@emmafiorentino.com.ar', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', 'Steve Humphreys'),
  ('cchapelain@yahoo.fr', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('ferkous@ideale.ma', 'prospect', 'pipedrive_import_2025', 'N. Africa', 'active', 'Steve Humphreys'),
  ('b.niemela@print.de', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('m.seidl@pp-europe.eu', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('a.dyck@print.de', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('dmazurek@unit.com.pl', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('mlkinturi@gmail.com', 'prospect', 'pipedrive_import_2025', 'Scandenavia', 'active', 'Steve Humphreys'),
  ('bobneubauer@napco.com', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('gofromagazine@gmail.com', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('sarah@proprint.com.au', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('paul@australianprinter.com.au', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('sabine@eastwest-pr.com', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('editor@globalprintmonitor.info', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('4 It Group', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Argentina Grafica Cromatica', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('AD Communications', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ashville', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Ashville Media Group', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Birkner GmbH & Co. KG', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Caractere', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Colourfast', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('redaction@infopresse.com', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Deutscher Drucker', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Digital Labels & Packaging magazine', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('DEUTSCHER DRUCKER VERLAG  � eine Unit de', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Digital Dots', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Digital Printer', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Earth Island Publishing (Print Solutions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Earth Island', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Enviroment Times', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('G.S.N Raju', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Hanmail', 'prospect', 'pipedrive_import_2025', 'South Korea', 'active', 'Steve Humphreys'),
  ('selection@infopresse.com', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Gramani', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Image reports Magazine', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Indian Printer and Publisher (IPP Group)', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Intelligent Media', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('In Publishing', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Indonesia Print Media', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('IPW Online', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Redaktion@SCM.dk', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Kursiv', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('Large Format Review', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Labels and Labeling', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Majalah Grafika Indonesia', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('LinkPublishing', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Redaktion@Installator.dk', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Redaktion@Designbase.dk', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Redaktion@Designbase.se', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('All about newspapers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('AGI.SE', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Arte Grafica', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', 'Steve Humphreys'),
  ('Binstead Group', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('BNO', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Banas', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Callum Publishing', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Delhi Printer', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Comeddiance', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Draeger', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



