-- Batch 26 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('iprint ok', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Iscan Dis Ticaret Makina Pazarlama Ltd', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('ISEC Lisboa', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('ISOVOLTA SAU', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('ISS', 'prospect', 'pipedrive_import_2025', 'Congo', 'active', 'Steve Humphreys'),
  ('Ipex Printing Press', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('It Graphic AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Italgraf Media AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('ITC', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Itaxa', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('Ituren Encuadernaciones, s.l.', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Iuye r g', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('iWin', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('Jaakkoo-Taara Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('JAD Automation', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Jag Media', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Jagdamb Enterprises', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jai Graphics', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Jayam Prints', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jain Computer Services', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jayakarta Agung Offset', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Jane Buurman Handmade', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('ITelecom AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Jazz Traders & Exports', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jenevra Group Ltd', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', 'Steve Humphreys'),
  ('Jerashi', 'prospect', 'pipedrive_import_2025', 'Palestine', 'active', 'Steve Humphreys'),
  ('Jianli Eco Products', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jianlong', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Jinnest�l Etikett AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Jire Print & Com', 'prospect', 'pipedrive_import_2025', 'Cameroon', 'active', 'Steve Humphreys'),
  ('Jitog', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('JK Trading', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('JLSPRINT CONSULTING', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Jodi Etiketter AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Johnswood Press', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Jordan Walls', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('Jose Antonio Garcia', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Jos� Antonio Rubio Lavin', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Jose da Mata', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Jannes Snabbtryck Ab', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Jose Miguel Sanchez Sch', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Jouna Print Posters LLC', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Joyceprint Ltd', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Jurado Impresores', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', 'Steve Humphreys'),
  ('JUNGANGTECH', 'prospect', 'pipedrive_import_2025', 'Korea', 'active', 'Steve Humphreys'),
  ('Jusida', 'prospect', 'pipedrive_import_2025', 'Lithuania', 'active', 'Steve Humphreys'),
  ('Just Offset', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Jyv�sseudun Paino Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('K Joshi & Co', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Jeddah Graphic Center', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('K. Brasch & Co., Ltd.', 'prospect', 'pipedrive_import_2025', 'Japan', 'active', 'Steve Humphreys'),
  ('Kakkar Graphics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kalaa Sarg', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kahkashan Computer Press', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kalidera Printing Group', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Kallenberg Tekstiltrykk As', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kalpatharu chemicals', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kamal', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kanonkopia AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Kardplus', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Karim Jacob', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', 'Steve Humphreys'),
  ('JL-Tarra Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Karlssons Grafiska AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('KARMA FLEX', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Karm�y Trykkeri as', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kartgraphix Limited', 'prospect', 'pipedrive_import_2025', 'Uganda', 'active', 'Steve Humphreys'),
  ('Karthika Graphicx', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Karya Adi Grafika', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Kashoba Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kasturi Graphics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('KATHOO ID CARDS', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kee NonWovens', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Keeco Creative Ltd', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Kerd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Kenyon Printers', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Kern Profilering AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Keski-Suomen Sivu Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Jowan Future Design', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('JR Etikett', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Kalenderforlaget AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kalmar Kuvert Sweden AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('karaky Printing Press', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Kemanes Print', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('Keski-Suomen Painotuote Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Khattab', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('Khatri Paper Bag', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Khairan Printing Press', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('khawam Group', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Khilim', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('KHL Printing Co Pte Ltd', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Ki�nt�l� UG Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Killin Kopio Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Kingdom Printers', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Kimoha', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Kirjapaino �ss� Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Kirjapaino Hermes Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Kirjapaino Kari Ky', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Kias Reklame As', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Kirjapaino Laine Direct Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Kirjapaino Markprint Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



