-- Batch 45 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Druck Medien', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', 'Steve Humphreys'),
  ('DTP', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Easy Net', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Edinova', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Fach Gruppe', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', 'Steve Humphreys'),
  ('Falkmedia', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Flexography', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Febelgra', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Forestry Journal', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Grafix', 'prospect', 'pipedrive_import_2025', 'Far East', 'active', 'Steve Humphreys'),
  ('GPA-DJP', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Graphic Monthly', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Graphic Arts Monthly', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Graph Print', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Gremi', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Handelsblatt', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Horisontgruppen', 'prospect', 'pipedrive_import_2025', 'Denmark', 'active', 'Steve Humphreys'),
  ('Igud', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', 'Steve Humphreys'),
  ('Heise', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('info@haymarket.de', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('IndustriaGraphica', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('IPA', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Intergraficas', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Kauppalehti', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Journalisten', 'prospect', 'pipedrive_import_2025', 'Denmark', 'active', 'Steve Humphreys'),
  ('Keyin', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Lets Recycle', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Kvgo', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Lupe', 'prospect', 'pipedrive_import_2025', 'Hungary', 'active', 'Steve Humphreys'),
  ('Manstein', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', 'Steve Humphreys'),
  ('Matbaa Haber (Turkish Printing Magazine)', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Matbaa&teknik', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Marmai', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Multi Tech, PR', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('ME Printer', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('NAPCO Media', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Neil D Stratton', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Nichima', 'prospect', 'pipedrive_import_2025', 'Japan', 'active', 'Steve Humphreys'),
  ('Packaging MEA (JJ Media Fz LLC)', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Office ABC', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Papetierdefance', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Paperage', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Manstein1', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('PFA Hodorogea Virgiliu Vasile (Virgiliu&', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Poligrafica', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Pixel Power', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Print News', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Print&Media Publishing Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Print2Pack', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Printernet', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Printing Connect Online', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printing Impressions', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('PrintLink', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Printweek UK', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Products and Services review', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('MSA.Hinet', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Publish.ru', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('Promenade Group', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Quicknet Trading', 'prospect', 'pipedrive_import_2025', 'Ethiopia', 'active', 'Steve Humphreys'),
  ('Repro House Ltd', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Roularta', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Scrikss', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Sentient  Publishing', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Netvigator', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Sign Graphic', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('SignLink', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Swiatdruku', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Technichenouve', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('WHERE To Print Magazine', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Whitmar', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Whitmar Publications�', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('WNIP', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('NMG', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Papetier De France', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Penton', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Philprinting', 'prospect', 'pipedrive_import_2025', 'Far East', 'active', 'Steve Humphreys'),
  ('Plastik-Ambalaj', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Poligrafika', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Polimag', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', 'Steve Humphreys'),
  ('Poost', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('PolyMedia', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('Prepress_OP', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', 'Steve Humphreys'),
  ('Prepressworld', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', 'Steve Humphreys'),
  ('Press contact North Africa', 'prospect', 'pipedrive_import_2025', 'N. Africa', 'active', 'Steve Humphreys'),
  ('Print NZ', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Print5931', 'prospect', 'pipedrive_import_2025', 'Korea', 'active', 'Steve Humphreys'),
  ('Printing Review', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Printingfield', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Print-Publishing', 'prospect', 'pipedrive_import_2025', 'hungary', 'active', 'Steve Humphreys'),
  ('Publisher.ch', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('ReedBusiness', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Reed Business', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Redactiesign', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('RePrint', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('X-media', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', 'Steve Humphreys'),
  ('What They Think', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Universign', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Wanadoo', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('TYPO GR1', 'prospect', 'pipedrive_import_2025', 'Greece', 'active', 'Steve Humphreys'),
  ('Smedia Group', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



