-- Batch 46 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Sigma', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('STN', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Revistambientes', 'prospect', 'pipedrive_import_2025', 'South America', 'active', 'Steve Humphreys'),
  ('SGPresse', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Sanomelehdet', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Rathaus Press', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Vivuzu', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Printer Media Group', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Instantprint', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Industrieuse Fourmi Sarl', 'prospect', 'pipedrive_import_2025', 'Côte d''Ivoire', 'active', 'Steve Humphreys'),
  ('MSI Bindery Parts', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Theboise', 'prospect', 'pipedrive_import_2025', 'Rwanda', 'active', 'Steve Humphreys'),
  ('WBL GRÁFICA', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Printed Design', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Sheriar Press', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Ryansprintz', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Almahdipsc', 'prospect', 'pipedrive_import_2025', 'Afghanistan', 'active', 'Steve Humphreys'),
  ('Greens Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Pelipost', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Imprimatur Ltd', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', 'Steve Humphreys'),
  ('Sorbon Kodirov', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Emil Asenov', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', 'Steve Humphreys'),
  ('TMprinting', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Oscar Artes Graficas', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('EO Johnson Business Technologies', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Integrated Graphics Ltd', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Mohammed Alfarsi', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('Blunt Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('P Manjunath', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Duplo International Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('MCC Label Ireland', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Drkmode', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Introscan Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Paiboon Patsir', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Houston Research & Development Consultancy B.V.', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Cynthia Nine', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Oxford Graphic', 'prospect', 'pipedrive_import_2025', '415939', 'active', 'Steve Humphreys'),
  ('Island Printing & Finishing Equipment', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Apogee Corporation', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('C S Bindery Solutions Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('CJB Printing Equipment Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('CLC Presentation Systems', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Duplo UK', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Elmstok', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Encore Machinery Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Fingerprint Digital', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Flag Engineering Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Graphic West Packaging', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Kolbus UK Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Lawhill Paper Handeling Systems Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('M & D Marketing Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Midland Machinery Supplies Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Moll International', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Nyland Graphics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('PDC Presentation Solutions Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Perfect Bindery Solutions LLP', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Pitney Bowes', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printaply', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Finishing Point TFP Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Finishing Point (TFP) LTD', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Punchbind Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Repro Lines', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Zerographic Systems Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Foto Studio el Sueno', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('SENEFELDER COMERCIO E REPRESENTAÇÕES', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('YPD Creative', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('German Pantozzi', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', 'Steve Humphreys'),
  ('Xerographic Copy Center', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Mart Smiths', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print Partnership Reprograhics LTD', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Sign Update & Image Reports', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Harrington', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('EveryPage', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Imprimerie ICP', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('HANSUNG P&C', 'prospect', 'pipedrive_import_2025', 'South Korea', 'active', 'Steve Humphreys'),
  ('Hector Marin', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('PrintWeek India', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Gilmore Global', 'prospect', 'pipedrive_import_2025', 'Canada', 'active', 'Steve Humphreys'),
  ('JS impresores', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Minh Duc solutions joint stock company', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', 'Steve Humphreys'),
  ('Corrugadora Los Andes SRL', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', 'Steve Humphreys'),
  ('Scanright', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Martha Bugeja', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Makeist', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Gráfica Suiza', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Precision Press', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Print on Demand Ltd', 'prospect', 'pipedrive_import_2025', 'Trinidad and Tobago', 'active', 'Steve Humphreys'),
  ('Mohammed Benabissi', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('Diamond Digital', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mark Andy', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('UMC Print', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Dennis Maps Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Lucas Lopez', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Prinya Denpatcharangkul', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Sage Document Services Group', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Mail House Inc.', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Stickpack', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Rowtype Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('John Williams', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Commercial Foundation', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



