-- Batch 11 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Regency Print', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Printni.com', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Desktop', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', 'Steve Humphreys'),
  ('Banbury Print & Design', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('nuprint', 'prospect', 'pipedrive_import_2025', 'Northern Ireland', 'active', 'Steve Humphreys'),
  ('Oakdene Services', 'prospect', 'pipedrive_import_2025', 'N.Ireland', 'active', 'Steve Humphreys'),
  ('A4 Desing & Print Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Image Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Mlg Glasgow', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Wordworks Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Akm Design & Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Clear signs', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Craig & Stewart Printers', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Hopwood', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Front Line Promotions', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Queen Margaret - Service Point Edinburgh', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('The Shetland Times', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Glasgow Press', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Ink on paper', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Mainstream Print and Design', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Ghdigital', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Pointer Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Hall Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Juna Digital', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('A J Green', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Interlith (Derby) Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('255 Roseprint', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Dimension Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Hounsfield Printing', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('I Q Digital House Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('EA Digital', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Arthur Rostron & Sons Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Unison Colour', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Uthara Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print Options (SW) Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printech Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bicester Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('In Touch Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Precision Signs', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Pipi', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Doculand', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Panopus Reprographic', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print Wizards', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('QQD Design and Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Aztec Colour Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Modern Colour Solutions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('London School Economics & Political Scie', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Design Print Management Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Premiere Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('PontaPrint', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Nightingale Press Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Reed Europe', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Shipley Creative', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('KER Graphics Ltd', 'prospect', 'pipedrive_import_2025', 'Northern Ireland', 'active', 'Steve Humphreys'),
  ('Copymade Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Im Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Arkay Imaging', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Social Print and Copy CIC', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('University of Edinburgh', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Rannoch Press', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Premier Printworks', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Thomson Print & Packaging Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Custom Works', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Beaver Custom Printing', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Larbert Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Mod', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('PG Paper', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Ardrossan Printing Company Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Wades Print & Design', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Ivanhoe Caledonian', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Invision Sign and Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('imagepixel', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Papergraphics', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('University of West Scotland', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Hobs Reprographics', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('A+M Imaging Services', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Bannister and Gasp Digital Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('The Web Print & Sign', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Solway Offset Services', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Linn Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Creative Graffix', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Hill & Hay', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Print Vision Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('The Copy and Print Shop', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Owl Design & Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Events Armoury Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Kolorkey Printing', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Langstane Press Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Winter & Simpson Print', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('West Port Print & Design', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Ambro Packaging & Presentation Products', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Steve Humphreys'),
  ('Honeycomb Print Services', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Label Source', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('CanvasBayUK ltd', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Minuteman Press Cardiff', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Bert Edwards (milford Haven) Limi', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Flagship Signs', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Dial-A-Print', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('E L Jones & Sons', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Pace Print (Edinburgh) Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



