-- Batch 5 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Queens University Belfast School Of Chem', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Yps', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Erapa (UK) Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Larchfield Associates Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Flo-Print Nottingham', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mailroom Equipment Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Tawny Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('C D C S', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Manor Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Reflex Print Solutions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Simpson Group', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print Direct Solutions Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bross Print & Design', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('University Of Derby', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Thurston Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Dentons Uk & Middle East Llp', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('GWR Design & Illustration', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Control Induction', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Online Reprographics Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('MB Creative Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('EC Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mensa Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Rockwell Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printing and Graphic Machinery', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Design & Print Solutions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Evolution Design and Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('PDS Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('G. D. Copy Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Stockport Cutting Formes Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Enders', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Newark Designer Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cambridge University Hospital Nhs Founda', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('North Account Book Mfg Co;', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ha''Penny Press Ltd.', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Benhill Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Abstrakt Services Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ram Singh Photographers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Deluxe Printers Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Orient Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Lovell Johns Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mantech', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('silverline graphics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Power Print', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Hamilton Forms', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Hak Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Quacks Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Sac Graphics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Gallaher', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Photogenic', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mailboxes etc', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Whites', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Dataforms Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Autobind Denby Dale', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ink Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ling Design Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Russell Printers Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('DIGIPRESS PRINTERS', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Century Studios Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('NHS', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Itek Bolton Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Minuteman Press Stockport', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Universal Screen & Digital Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Tasker Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Taylor Thorne Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Big! Huge! Massive!', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('N W PRINT LTD', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Signature Signs Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Colourbridge South West Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Lavender Avenue', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Number 1 Golf Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('OTM', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Dolphin Graphics', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Headline Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Dearnex', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('The Art File', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('All Print Display Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Sps Print Group', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('RPG Innovations Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Southstream Services Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Zippy Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cherry Box Design Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('After Hours Creative Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('P AND J PRINT', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Perfect Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Managed Technology Corporation Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Banana Uk Media', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('MFN & RE TAME', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Prontaprint Stratford', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Guys & St Thomas Nhs Foundation Trust', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Eagle Promotions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Indigo Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Oxley''s', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Benchmark Reprographics Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('28Celsius', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Serious Fraud Office', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Jd Printing Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Tangerine Red', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Envoprint', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Sonar Duplication Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printstore', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



