-- Batch 41 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Adonis Allou', 'prospect', 'pipedrive_import_2025', 'Ivory Coast', 'active', 'Steve Humphreys'),
  ('Afzal Farook', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Aditya Kshirsagar', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Zeej Print', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Ahmed Sayed', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('Aleksandra', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('Alexander Van Der Putt', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Alathea Ferrand', 'prospect', 'pipedrive_import_2025', 'French Polynesia', 'active', 'Steve Humphreys'),
  ('Albert Rios', 'prospect', 'pipedrive_import_2025', 'Panama', 'active', 'Steve Humphreys'),
  ('Alexandru Suciu', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Alexis Gonzalez', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', 'Steve Humphreys'),
  ('Ali - card creaser', 'prospect', 'pipedrive_import_2025', 'Iraq', 'active', 'Steve Humphreys'),
  ('Alfred Vella', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Ali', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Ali Zand', 'prospect', 'pipedrive_import_2025', 'Iraq', 'active', 'Steve Humphreys'),
  ('Allan', 'prospect', 'pipedrive_import_2025', 'Uganda', 'active', 'Steve Humphreys'),
  ('Allan Krautz', 'prospect', 'pipedrive_import_2025', 'Denmark', 'active', 'Steve Humphreys'),
  ('Allen Odiase', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Amer', 'prospect', 'pipedrive_import_2025', 'Syria', 'active', 'Steve Humphreys'),
  ('Alvis Lacis', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Alvin Tan', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Zoom Grafisk', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Amer Ditta', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Amir Rahman', 'prospect', 'pipedrive_import_2025', 'Kuwait', 'active', 'Steve Humphreys'),
  ('Amjad Al Hyasat', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Andrei Iacob', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', 'Steve Humphreys'),
  ('Anil Desai', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Antje Collis', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Angelo Visconti', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Anthony Owusuansah', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Antonio Sanchez', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Antonie Ayite d''Almeida', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Antonio S�nchez Lozano', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Arifur Rahman', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('Arun Nk', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Artur', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Asghar Kamal', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Aubin', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', 'Steve Humphreys'),
  ('Audrey Osias', 'prospect', 'pipedrive_import_2025', 'Reunion', 'active', 'Steve Humphreys'),
  ('Auker Medina', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ayman Sasa', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('Badr-Eddine', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('Bekir Baspinar', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Behar Krasniqi', 'prospect', 'pipedrive_import_2025', 'Kosovo', 'active', 'Steve Humphreys'),
  ('Bart Vanderschueren', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Bennette Armah Hanson', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Ben Bouchta Mohamed', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ben Roca', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('Bora Printer', 'prospect', 'pipedrive_import_2025', 'Cambodia', 'active', 'Steve Humphreys'),
  ('Bhaskar Sj', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Briandt Emmanuel', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Carlo Mini', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Brendan', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Charles Agwadike', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Chandrakant Sinha', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Christian Gariboldi', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Ciaran Guinan', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Cipriano Napala', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Cristian Fernando Infante', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Cristian Molina', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Colin Yung', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', 'Steve Humphreys'),
  ('Daniel Consuegra', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Danilo Ricci', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('David', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Debesh Chanda', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Deepak Rava', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Dickson Lee', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Dejan Ilic', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Desmond Otakponmwen', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('DILIP', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Dima Ostrozhni', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Diogo Teixeira', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Dominic', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Doreen Mulroy', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Edmund Kuna', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Dr Abdulaziz Almohimeed', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Efint', 'prospect', 'pipedrive_import_2025', 'Korea', 'active', 'Steve Humphreys'),
  ('Efrain Salazar', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Efrem Belay', 'prospect', 'pipedrive_import_2025', 'Ethiopia', 'active', 'Steve Humphreys'),
  ('Ekanem EFFIONG', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Elimar de Aguilar', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Emad', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Erick Simiyu', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('Emilio Koullouros', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('Ernesto Oleaga', 'prospect', 'pipedrive_import_2025', 'Uruguay', 'active', 'Steve Humphreys'),
  ('Faisal', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Eugenijus Noreika', 'prospect', 'pipedrive_import_2025', 'Lithuania', 'active', 'Steve Humphreys'),
  ('Fateme Kahvand', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Francesca Romana', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Fr�d�ric Reiser', 'prospect', 'pipedrive_import_2025', 'Luxembourg', 'active', 'Steve Humphreys'),
  ('Francesco Annunziata', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Fredrik', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('frangetha', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Gabi S', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('G. Grimaldi', 'prospect', 'pipedrive_import_2025', 'Sudan', 'active', 'Steve Humphreys'),
  ('Gabriel Susca', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Ganapathiram Natarajan', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ganesh Ingle', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Gisli Hjartarson', 'prospect', 'pipedrive_import_2025', 'Iceland', 'active', 'Steve Humphreys'),
  ('Giuseppe Josegraph', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



