-- Batch 12 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Keltic Design & Print', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Caxton Press', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Spectrum Printing', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Graphic Realm', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Cyfres Eryri', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Keith Brown & Sons Ltd', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Down Town Secure Books', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('The Print Place', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('ALS Printing', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('University of South Wales', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Castell Howard Foods Ltd', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('RG Peate Funeral Services', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('W Williams & Son', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Davies Printing', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Celtic Reflections', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Foundry Printing Works', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Tech-Print', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Palm Signs', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Print Speed', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('University of Salford', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Sign O Graphics Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Kingston Grammar School', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Jag Beauty & Shaving Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Brown Bros (Irvine) Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Gavin Watson Printers', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('SML', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('The New Ink Printing Co. Ltd.', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('APS Printers', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Artebook', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Tantallon Press Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Star Print', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Prontaprint Tamworth', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Gipping Press Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Hallmark Cards', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Rufford Printing Co', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Wigston Paper', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Minster Press', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Crayon Juice Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Polstead Press', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('University of Huddersfield', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Veriworks', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('CALEY PRINT AND STATIONERY LTD', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Kershaw Print', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Guardian Press (Boston) Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('SubExotic', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Express Signs & Engraving', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Photo Solutions', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Betteridge', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Quadrant Print & Design Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Mike Clarke Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Kingston University', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Smarts', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Plusprint', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Goldsmiths, Uni of London', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Leiston Press', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Thomas Fattorini Ltd - Namebadges', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('James Cropper PLC', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Whitesprint', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Bangor University', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Jigsaw Print', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Hyphen UK Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ian Douglas Design & Print Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Modern Graphics', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('M P C Labels', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Xerox Uk Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('City Press Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ddb International', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Jo Bie Design', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Kama', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Precision Photofabrication Developments', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('K J S Print To Mail Services Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Minuteman Press Belfast', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Teknodesign', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Sole Trader', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('D M L Digital Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Hillsons', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('AVON BOOK BINDING', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Loughborough University', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Northumbria University', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Print Matters', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Red43.co.uk', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Custom Clothing', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('DISPLAY TRADE', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Eviosys', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('The Highfield School', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Delta Displays Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Interprint Associates', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('MJR Printers', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('City Print', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Neil Smy & Associates', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('D Isom (printers) Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Queen Mary, University of London', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Print Revolution Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Paul Everett Print & Design', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Meers Graphics & Print', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('University of Manchester', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Printinc', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Footprintz', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Ace Cutters( London) Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('McKenzie Quality Print', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



