-- Batch 16 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Apex Media', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('Apik', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Apis Technology Limited', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', 'Steve Humphreys'),
  ('APM (New Zealand) Ltd', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('APR', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('April Integra', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Arabian Hand Trad. & Cont.', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Arabian Impressions', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', 'Steve Humphreys'),
  ('Arc Document Solutions pvt ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Archies Enterprises', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Arctic Doll', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Areal Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Arab House for Printing', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Argus Printing', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('Arizona Plus', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Arkitektkopia Kalmar', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('ARPROS Gregor Lesjak s.p.', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Art impact', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Art O Print', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('ARTEGRAFICO', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Art Throb Typesetters', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('ARTE DIGITAL SA', 'prospect', 'pipedrive_import_2025', 'Nicaragua', 'active', 'Steve Humphreys'),
  ('Aras Reklam', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('�rtemis Graphic', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Artes Gráficas Sinaloenses', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('ARTES GRÁFICAS', 'prospect', 'pipedrive_import_2025', 'MEXICO', 'active', 'Steve Humphreys'),
  ('Artes Graficas', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Artipol', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Artoos Group', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Artizan', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Artprint promet', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Ark Trykk AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Artrender Industries', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('ASAN PACK', 'prospect', 'pipedrive_import_2025', 'Iran', 'active', 'Steve Humphreys'),
  ('Arwa Printing Press', 'prospect', 'pipedrive_import_2025', 'Kuwait', 'active', 'Steve Humphreys'),
  ('Asia Repro', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Ashwini Herbal Cosmetics', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Ashton Trading Limited', 'prospect', 'pipedrive_import_2025', 'Zambia', 'active', 'Steve Humphreys'),
  ('Asistencia Digital', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Asiatic Printing Press LLC', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Asian Development Bank', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Assam paper& printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Arkitektkopia', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Assempahfie Graphics', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', 'Steve Humphreys'),
  ('Atelier Printing Complex', 'prospect', 'pipedrive_import_2025', 'Ukraine', 'active', 'Steve Humphreys'),
  ('AST Digital print centre', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('atGraphiken AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Atlantic Benelux', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Atlas Axillia Company', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('�tta.45 Tryckeri | Kaltes Grafiska AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('�tta.45 Tryckeri AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Auraq Publications', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Auracons', 'prospect', 'pipedrive_import_2025', 'Lebanon', 'active', 'Steve Humphreys'),
  ('Arkitektkopia Halmstad', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Aurous Intertrade', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Avantika Printers Private Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Aut�nomo', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('AVINASHILINGAM UNIVERSITY', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Aviprint Prim SRL', 'prospect', 'pipedrive_import_2025', 'Moldova', 'active', 'Steve Humphreys'),
  ('Aw kreasindo', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('AVM Copy Center', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Avseth press and publicity', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Ayurkalpa', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Arkitektkopia J�nk�ping', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('AZprint', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Azteca Press', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('B & R Digitals', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('B&T Ontwerp', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('Bab�n Plus, S.L', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Bacetof and Associates', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Arkitektkopia Norrk�ping', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Bader H�rstwald-Immobilien AG', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('Arkitektkopia Nyk�ping', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Arkitektkopia �stersund', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Arkitektkopia Skellefte�', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Arkitektkopia Trollh�ttan', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Arkitektkopia Uddevalla', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Arne Backman Information AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Arteria AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Artsy Craft', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('�s� Association Council', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Aspire Printing Press', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', 'Steve Humphreys'),
  ('Atac Reklame', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Avery Dennison NTP AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('AVM Office Services', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('B2B Print', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Bahr Al Hurouf for printing press', 'prospect', 'pipedrive_import_2025', 'Iraq', 'active', 'Steve Humphreys'),
  ('Baheer computer & Printing Co. Ltd', 'prospect', 'pipedrive_import_2025', 'Afghanistan', 'active', 'Steve Humphreys'),
  ('Balaji sales', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Badlab Design di Angarola Marco', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('Balaji Colour Prints', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('BAHUCHAR OFFSET', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Banderoll.se', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Balox Corp', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Bar Code Print Svenska AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Banma', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Barsoom Enterprise & Sourcing (Pty) Ltd', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Bauener', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Basudev Computer', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('BATCO', 'prospect', 'pipedrive_import_2025', 'Bahamas', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



