-- Batch 29 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Mid Digital Solutions', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Min Hwa Envelope Manufacturers Pte Ltd', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Million Printing', 'prospect', 'pipedrive_import_2025', 'China', 'active', 'Steve Humphreys'),
  ('Manipulados Graficos Orpi S.L', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Mindanao State University', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Ministry of Finance', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Ministry of Interior', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', 'Steve Humphreys'),
  ('Mino-Tuote Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Minuteman Press Caringbah', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('MIP', 'prospect', 'pipedrive_import_2025', 'Tunisia', 'active', 'Steve Humphreys'),
  ('Miss Print', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Marina', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', 'Steve Humphreys'),
  ('Mitra', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('MittMedia Print AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Mark�ren Reklame AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Matbaacilik Reklamcilik', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', 'Steve Humphreys'),
  ('Matinpaino', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Maxi Screen Skylt Reklam AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('maxroy.no Reklame & Advertising', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('MCC Sweden', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('McGowans', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Mediabaren i Stockholm AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Medtryck Sverige AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('MEGABRINDE UNIPESSOAL LDA', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Megaprint AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Megaskylt & Reklam i Uddevalla', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Merchant logo / L�nskopia i Lule� AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Mercury Graphics AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Messeveggen', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Middle East Printing Press', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', 'Steve Humphreys'),
  ('Milj�tryck I Ljusnanbygden Ab', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Mj�lby Tryckeri & Reklam AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Mix Grafiska AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('M-Kopia I Stockholm AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Mixiprint AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('MM', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Mm fibre packaging', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Modern Printers Offset', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Modern Printing Press', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Modularis', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('Mohamed', 'prospect', 'pipedrive_import_2025', 'Sierra Leone', 'active', 'Steve Humphreys'),
  ('Mohit Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Moltzau AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Molvik Grafisk AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Monocromo', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Mondo Nougat', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('monotag', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Monsieur Monot', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('MONTIMPREX', 'prospect', 'pipedrive_import_2025', 'Montenegro', 'active', 'Steve Humphreys'),
  ('Montrade', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('ML Tryck AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Moody Joe', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Mosaic Vision', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Mostori', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Mostakin Press', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('MOZAIK TISK d.o.o.', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', 'Steve Humphreys'),
  ('MPI Papers Private Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Mr Web', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('MODESIGN - Masters Of Design', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Mr. Repro', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('MS print', 'prospect', 'pipedrive_import_2025', 'Slovakia', 'active', 'Steve Humphreys'),
  ('Ms impresos', 'prospect', 'pipedrive_import_2025', 'Uruguay', 'active', 'Steve Humphreys'),
  ('MS Print', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', 'Steve Humphreys'),
  ('Mudrak', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Mudrana Printers', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Mudranshreeng', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Muhsin.com', 'prospect', 'pipedrive_import_2025', 'Iraq', 'active', 'Steve Humphreys'),
  ('M�klegaard Print Shop AS', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', 'Steve Humphreys'),
  ('Multi Hitech Inc', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Multi Print Oy / Grano Mikkeli', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Multi Service Graphiques', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', 'Steve Humphreys'),
  ('Multimpresos', 'prospect', 'pipedrive_import_2025', 'Columbia', 'active', 'Steve Humphreys'),
  ('MULTIPRESS PUBLICIDAD', 'prospect', 'pipedrive_import_2025', 'MEXICO', 'active', 'Steve Humphreys'),
  ('Multisolutions', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Mundo Grafic', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Music Vanog - Publicidad & Marketing', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Mutombo Trading', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Mustang Print', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('MVide', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('My cool cell', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Nabeel Printing Press', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Nacamura Co Ltd', 'prospect', 'pipedrive_import_2025', 'Japan', 'active', 'Steve Humphreys'),
  ('Naghsh & Neshan Printing', 'prospect', 'pipedrive_import_2025', 'Iran', 'active', 'Steve Humphreys'),
  ('Naili Printing Industry', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('MONSALVE MORENO', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', 'Steve Humphreys'),
  ('Najem printing press', 'prospect', 'pipedrive_import_2025', 'Kuwait', 'active', 'Steve Humphreys'),
  ('Najlabs', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('Nakladatelstv� P3K', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', 'Steve Humphreys'),
  ('Nakon Sp. z o.o.', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('NAranja', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', 'Steve Humphreys'),
  ('Naseer Ahmad', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('National Press', 'prospect', 'pipedrive_import_2025', 'Jordan', 'active', 'Steve Humphreys'),
  ('National Printing Press L.L.C', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Nateva COM', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('NAV G1', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Navin Digitech Pvt. Ltd.', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('More Print AB', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('NBA Studios', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Neelkanth Xerox', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Neha Offset Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



