-- Batch 45 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner, phone)
SELECT * FROM (VALUES
  ('Druck Medien', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', NULL, NULL),
  ('DTP', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', NULL, NULL),
  ('Easy Net', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, '61396627500'),
  ('Edinova', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, '00 39 02 21 580 21'),
  ('Fach Gruppe', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', NULL, NULL),
  ('Falkmedia', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('Flexography', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Febelgra', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', NULL, NULL),
  ('Forestry Journal', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01387 702272'),
  ('Grafix', 'prospect', 'pipedrive_import_2025', 'Far East', 'active', NULL, '00 61 2 9635 6059'),
  ('GPA-DJP', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Graphic Monthly', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Graphic Arts Monthly', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Graph Print', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', NULL, NULL),
  ('Gremi', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, NULL),
  ('Handelsblatt', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('Horisontgruppen', 'prospect', 'pipedrive_import_2025', 'Denmark', 'active', NULL, NULL),
  ('Igud', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', NULL, NULL),
  ('Heise', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('info@haymarket.de', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('IndustriaGraphica', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, NULL),
  ('IPA', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Intergraficas', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, NULL),
  ('Kauppalehti', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', NULL, NULL),
  ('Journalisten', 'prospect', 'pipedrive_import_2025', 'Denmark', 'active', NULL, NULL),
  ('Keyin', 'prospect', 'pipedrive_import_2025', 'China', 'active', NULL, NULL),
  ('Lets Recycle', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '0117 907 4107'),
  ('Kvgo', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, NULL),
  ('Lupe', 'prospect', 'pipedrive_import_2025', 'Hungary', 'active', NULL, NULL),
  ('Manstein', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', NULL, NULL),
  ('Matbaa Haber (Turkish Printing Magazine)', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, NULL),
  ('Matbaa&teknik', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, NULL),
  ('Marmai', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', NULL, NULL),
  ('Multi Tech, PR', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('ME Printer', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, '''+971 55 9381589'),
  ('NAPCO Media', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, '(630)323-8934'),
  ('Neil D Stratton', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Nichima', 'prospect', 'pipedrive_import_2025', 'Japan', 'active', NULL, '00 81 3 3265 5461'),
  ('Packaging MEA (JJ Media Fz LLC)', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, '''+971 4 3873575'),
  ('Office ABC', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, '00 49 30 479071 18'),
  ('Papetierdefance', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Paperage', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Manstein1', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('PFA Hodorogea Virgiliu Vasile (Virgiliu&', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', NULL, NULL),
  ('Poligrafica', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, '00 48 22 828-14-00'),
  ('Pixel Power', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '3.51911E+11'),
  ('Print News', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', NULL, NULL),
  ('Print&Media Publishing Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', NULL, NULL),
  ('Print2Pack', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', NULL, NULL),
  ('Printernet', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Printing Connect Online', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Printing Impressions', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('PrintLink', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Printweek UK', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '020 7738 5454, 020 7501 6680'),
  ('Products and Services review', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '0121 824 7700'),
  ('MSA.Hinet', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Publish.ru', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', NULL, NULL),
  ('Promenade Group', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01273 858 330'),
  ('Quicknet Trading', 'prospect', 'pipedrive_import_2025', 'Ethiopia', 'active', NULL, '00251912964400'),
  ('Repro House Ltd', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Roularta', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', NULL, NULL),
  ('Scrikss', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, '00 90 212 511 76 57'),
  ('Sentient  Publishing', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', NULL, NULL),
  ('Netvigator', 'prospect', 'pipedrive_import_2025', 'China', 'active', NULL, NULL),
  ('Sign Graphic', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, NULL),
  ('SignLink', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Swiatdruku', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, NULL),
  ('Technichenouve', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, '00 39 02 39 090 352'),
  ('WHERE To Print Magazine', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', NULL, '''+234(0)803 862 9114'),
  ('Whitmar', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Whitmar Publications�', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07792 037780'),
  ('WNIP', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '0770 392 4448'),
  ('NMG', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('Papetier De France', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Penton', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Philprinting', 'prospect', 'pipedrive_import_2025', 'Far East', 'active', NULL, NULL),
  ('Plastik-Ambalaj', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, NULL),
  ('Poligrafika', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, NULL),
  ('Polimag', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', NULL, NULL),
  ('Poost', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, NULL),
  ('PolyMedia', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', NULL, NULL),
  ('Prepress_OP', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', NULL, NULL),
  ('Prepressworld', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('Press contact North Africa', 'prospect', 'pipedrive_import_2025', 'N. Africa', 'active', NULL, NULL),
  ('Print NZ', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', NULL, NULL),
  ('Print5931', 'prospect', 'pipedrive_import_2025', 'Korea', 'active', NULL, NULL),
  ('Printing Review', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '''+91 1122141542'),
  ('Printingfield', 'prospect', 'pipedrive_import_2025', 'China', 'active', NULL, NULL),
  ('Print-Publishing', 'prospect', 'pipedrive_import_2025', 'hungary', 'active', NULL, NULL),
  ('Publisher.ch', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', NULL, NULL),
  ('ReedBusiness', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Reed Business', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Redactiesign', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, NULL),
  ('RePrint', 'prospect', 'pipedrive_import_2025', 'China', 'active', NULL, NULL),
  ('X-media', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', NULL, NULL),
  ('What They Think', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Universign', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', NULL, NULL),
  ('Wanadoo', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('TYPO GR1', 'prospect', 'pipedrive_import_2025', 'Greece', 'active', NULL, NULL),
  ('Smedia Group', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL)
) AS v(company_name, type, source, country, status, account_owner, phone)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



