-- Batch 41 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner, phone)
SELECT * FROM (VALUES
  ('Adonis Allou', 'prospect', 'pipedrive_import_2025', 'Ivory Coast', 'active', NULL, NULL),
  ('Afzal Farook', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', NULL, NULL),
  ('Aditya Kshirsagar', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '7385515229'),
  ('Zeej Print', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', NULL, '9.66114E+11'),
  ('Ahmed Sayed', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', NULL, NULL),
  ('Aleksandra', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', NULL, NULL),
  ('Alexander Van Der Putt', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Alathea Ferrand', 'prospect', 'pipedrive_import_2025', 'French Polynesia', 'active', NULL, NULL),
  ('Albert Rios', 'prospect', 'pipedrive_import_2025', 'Panama', 'active', NULL, NULL),
  ('Alexandru Suciu', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', NULL, NULL),
  ('Alexis Gonzalez', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', NULL, NULL),
  ('Ali - card creaser', 'prospect', 'pipedrive_import_2025', 'Iraq', 'active', NULL, NULL),
  ('Alfred Vella', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', NULL, '99009922'),
  ('Ali', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', NULL, '00966 562 224 242'),
  ('Ali Zand', 'prospect', 'pipedrive_import_2025', 'Iraq', 'active', NULL, NULL),
  ('Allan', 'prospect', 'pipedrive_import_2025', 'Uganda', 'active', NULL, NULL),
  ('Allan Krautz', 'prospect', 'pipedrive_import_2025', 'Denmark', 'active', NULL, NULL),
  ('Allen Odiase', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Amer', 'prospect', 'pipedrive_import_2025', 'Syria', 'active', NULL, NULL),
  ('Alvis Lacis', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Alvin Tan', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', NULL, NULL),
  ('Zoom Grafisk', 'prospect', 'pipedrive_import_2025', 'Norway', 'active', NULL, '''+47 32 26 64 50'),
  ('Amer Ditta', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Amir Rahman', 'prospect', 'pipedrive_import_2025', 'Kuwait', 'active', NULL, '96566235308'),
  ('Amjad Al Hyasat', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', NULL, '9626 5533 788'),
  ('Andrei Iacob', 'prospect', 'pipedrive_import_2025', 'Austria', 'active', NULL, NULL),
  ('Anil Desai', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Antje Collis', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, NULL),
  ('Angelo Visconti', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, '3384401533'),
  ('Anthony Owusuansah', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', NULL, NULL),
  ('Antonio Sanchez', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', NULL, NULL),
  ('Antonie Ayite d''Almeida', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', NULL, '228 2222 5326'),
  ('Antonio S�nchez Lozano', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, '34953444111'),
  ('Arifur Rahman', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', NULL, NULL),
  ('Arun Nk', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Artur', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, NULL),
  ('Asghar Kamal', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, NULL),
  ('Aubin', 'prospect', 'pipedrive_import_2025', 'Bahrain', 'active', NULL, NULL),
  ('Audrey Osias', 'prospect', 'pipedrive_import_2025', 'Reunion', 'active', NULL, NULL),
  ('Auker Medina', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Ayman Sasa', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', NULL, NULL),
  ('Badr-Eddine', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', NULL, '213550250400'),
  ('Bekir Baspinar', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, '05339679651'),
  ('Behar Krasniqi', 'prospect', 'pipedrive_import_2025', 'Kosovo', 'active', NULL, NULL),
  ('Bart Vanderschueren', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', NULL, NULL),
  ('Bennette Armah Hanson', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', NULL, '0244 331 028'),
  ('Ben Bouchta Mohamed', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Ben Roca', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', NULL, NULL),
  ('Bora Printer', 'prospect', 'pipedrive_import_2025', 'Cambodia', 'active', NULL, NULL),
  ('Bhaskar Sj', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '(831)730-7850'),
  ('Briandt Emmanuel', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', NULL, '''+233 244 560 108'),
  ('Carlo Mini', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', NULL, NULL),
  ('Brendan', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Charles Agwadike', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', NULL, '08038187818'),
  ('Chandrakant Sinha', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Christian Gariboldi', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, NULL),
  ('Ciaran Guinan', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Cipriano Napala', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, NULL),
  ('Cristian Fernando Infante', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, NULL),
  ('Cristian Molina', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Colin Yung', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', NULL, NULL),
  ('Daniel Consuegra', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, NULL),
  ('Danilo Ricci', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, '(333)434-5999'),
  ('David', 'prospect', 'pipedrive_import_2025', 'China', 'active', NULL, NULL),
  ('Debesh Chanda', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', NULL, '2.34803E+12'),
  ('Deepak Rava', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Dickson Lee', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', NULL, '''+65 9729 2562'),
  ('Dejan Ilic', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Desmond Otakponmwen', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('DILIP', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Dima Ostrozhni', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Diogo Teixeira', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '351 255 539230'),
  ('Dominic', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Doreen Mulroy', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Edmund Kuna', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Dr Abdulaziz Almohimeed', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', NULL, NULL),
  ('Efint', 'prospect', 'pipedrive_import_2025', 'Korea', 'active', NULL, NULL),
  ('Efrain Salazar', 'prospect', 'pipedrive_import_2025', 'Ecuador', 'active', NULL, NULL),
  ('Efrem Belay', 'prospect', 'pipedrive_import_2025', 'Ethiopia', 'active', NULL, '''+251 913859723'),
  ('Ekanem EFFIONG', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', NULL, '''-5767'),
  ('Elimar de Aguilar', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '48 347 83900'),
  ('Emad', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Erick Simiyu', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', NULL, NULL),
  ('Emilio Koullouros', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', NULL, '357 2246 1144'),
  ('Ernesto Oleaga', 'prospect', 'pipedrive_import_2025', 'Uruguay', 'active', NULL, NULL),
  ('Faisal', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, NULL),
  ('Eugenijus Noreika', 'prospect', 'pipedrive_import_2025', 'Lithuania', 'active', NULL, NULL),
  ('Fateme Kahvand', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Francesca Romana', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, NULL),
  ('Fr�d�ric Reiser', 'prospect', 'pipedrive_import_2025', 'Luxembourg', 'active', NULL, '''+352 / 69 14 18 064'),
  ('Francesco Annunziata', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, NULL),
  ('Fredrik', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', NULL, NULL),
  ('frangetha', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Gabi S', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', NULL, NULL),
  ('G. Grimaldi', 'prospect', 'pipedrive_import_2025', 'Sudan', 'active', NULL, '249 1875 56474'),
  ('Gabriel Susca', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', NULL, NULL),
  ('Ganapathiram Natarajan', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Ganesh Ingle', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Gisli Hjartarson', 'prospect', 'pipedrive_import_2025', 'Iceland', 'active', NULL, '''+354 895 8375'),
  ('Giuseppe Josegraph', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, NULL)
) AS v(company_name, type, source, country, status, account_owner, phone)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



