-- Batch 46 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner, phone)
SELECT * FROM (VALUES
  ('Sigma', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, NULL),
  ('STN', 'prospect', 'pipedrive_import_2025', 'China', 'active', NULL, NULL),
  ('Revistambientes', 'prospect', 'pipedrive_import_2025', 'South America', 'active', NULL, NULL),
  ('SGPresse', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Sanomelehdet', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', NULL, NULL),
  ('Rathaus Press', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, NULL),
  ('Vivuzu', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, '0850 885 1564 , 0332 235 9545'),
  ('Printer Media Group', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Instantprint', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Industrieuse Fourmi Sarl', 'prospect', 'pipedrive_import_2025', 'Côte d''Ivoire', 'active', NULL, '0708398719'),
  ('MSI Bindery Parts', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Theboise', 'prospect', 'pipedrive_import_2025', 'Rwanda', 'active', NULL, '''+250781711700'),
  ('WBL GRÁFICA', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', NULL, '11 4674.6300'),
  ('Printed Design', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', NULL, '01261 838282'),
  ('Sheriar Press', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '12038565532'),
  ('Ryansprintz', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, '0874150453'),
  ('Almahdipsc', 'prospect', 'pipedrive_import_2025', 'Afghanistan', 'active', NULL, '''+93-78-650-5622'),
  ('Greens Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07990525203'),
  ('Pelipost', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Imprimatur Ltd', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', NULL, '''+359898200183'),
  ('Sorbon Kodirov', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Emil Asenov', 'prospect', 'pipedrive_import_2025', 'Bulgaria', 'active', NULL, NULL),
  ('TMprinting', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07477013303'),
  ('Oscar Artes Graficas', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, '922 626 749, 691 692 964'),
  ('EO Johnson Business Technologies', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '8443425365'),
  ('Integrated Graphics Ltd', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', NULL, '01446 500 680'),
  ('Mohammed Alfarsi', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', NULL, NULL),
  ('Blunt Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07768 372 547'),
  ('P Manjunath', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '9398766015'),
  ('Duplo International Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('MCC Label Ireland', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Drkmode', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Introscan Ltd', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', NULL, '0141 445 2587'),
  ('Paiboon Patsir', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '66819851931'),
  ('Houston Research & Development Consultancy B.V.', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, '0031 (0) 6 43007752, 0031 (0) 6 26520316'),
  ('Cynthia Nine', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '3042683609'),
  ('Oxford Graphic', 'prospect', 'pipedrive_import_2025', '415939', 'active', NULL, '6748 3898'),
  ('Island Printing & Finishing Equipment', 'prospect', 'pipedrive_import_2025', 'N. Ireland', 'active', NULL, NULL),
  ('Apogee Corporation', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('C S Bindery Solutions Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('CJB Printing Equipment Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('CLC Presentation Systems', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Duplo UK', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Elmstok', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Encore Machinery Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Fingerprint Digital', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Flag Engineering Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Graphic West Packaging', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Kolbus UK Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Lawhill Paper Handeling Systems Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('M & D Marketing Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Midland Machinery Supplies Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Moll International', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Nyland Graphics', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('PDC Presentation Solutions Limited', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Perfect Bindery Solutions LLP', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Pitney Bowes', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Printaply', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('The Finishing Point TFP Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('The Finishing Point (TFP) LTD', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Punchbind Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Repro Lines', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Zerographic Systems Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Foto Studio el Sueno', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '5039904525'),
  ('SENEFELDER COMERCIO E REPRESENTAÇÕES', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', NULL, NULL),
  ('YPD Creative', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('German Pantozzi', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', NULL, NULL),
  ('Xerographic Copy Center', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '(352) 375-0797'),
  ('Mart Smiths', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Print Partnership Reprograhics LTD', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', NULL, NULL),
  ('Sign Update & Image Reports', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01622 699 182'),
  ('Harrington', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', NULL, '0828298874'),
  ('EveryPage', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07841 452901'),
  ('Imprimerie ICP', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, '02 97 72 39 42'),
  ('HANSUNG P&C', 'prospect', 'pipedrive_import_2025', 'South Korea', 'active', NULL, NULL),
  ('Hector Marin', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', NULL, '5566312426'),
  ('PrintWeek India', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Gilmore Global', 'prospect', 'pipedrive_import_2025', 'Canada', 'active', NULL, NULL),
  ('JS impresores', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Minh Duc solutions joint stock company', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', NULL, NULL),
  ('Corrugadora Los Andes SRL', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', NULL, '1140879254, 54318443'),
  ('Scanright', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01621810373'),
  ('Martha Bugeja', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', NULL, '''+356 99030788'),
  ('Makeist', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, NULL),
  ('Gráfica Suiza', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', NULL, NULL),
  ('Precision Press', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '817-557-3000'),
  ('Print on Demand Ltd', 'prospect', 'pipedrive_import_2025', 'Trinidad and Tobago', 'active', NULL, '(868) 622 5627, (868) 622 9434'),
  ('Mohammed Benabissi', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', NULL, NULL),
  ('Diamond Digital', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '020 3006 8232'),
  ('Mark Andy', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, NULL),
  ('UMC Print', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '913-815-6230'),
  ('Dennis Maps Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07920 838299'),
  ('Lucas Lopez', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '933529408'),
  ('Prinya Denpatcharangkul', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '''+66812514495'),
  ('Sage Document Services Group', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '9178647929'),
  ('Mail House Inc.', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '2143738285'),
  ('Stickpack', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '9212271303'),
  ('Rowtype Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07904 117133'),
  ('John Williams', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', NULL, NULL),
  ('Commercial Foundation', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL)
) AS v(company_name, type, source, country, status, account_owner, phone)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



