-- Batch 44 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner, phone)
SELECT * FROM (VALUES
  ('Jra impresores', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', NULL, '3012090240'),
  ('Clampitt Paper', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('CA Ravish Lalani', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Print-Art Services Limited', 'prospect', 'pipedrive_import_2025', 'Trinidad & Tobago', 'active', NULL, '18686804383'),
  ('UK Leaflets Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '020 3832 2733'),
  ('Envelope printing Zurwerra AG', 'prospect', 'pipedrive_import_2025', 'Switzerland', 'active', NULL, '079 830 56 91'),
  ('Lgen', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Forever After Designs', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Robert Johnson', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '7035990617'),
  ('''+351 21 478 3363', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Reinld Printing', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '715-536-9537'),
  ('Gooseberry Creations', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '''+918401920534'),
  ('Ricardo Lérias', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '934893457'),
  ('Arteos Digital S.L.', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, '687902188'),
  ('Servigraf', 'prospect', 'pipedrive_import_2025', 'El Salvador', 'active', NULL, NULL),
  ('Print Technique', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', NULL, '076 519 7402'),
  ('Suresh Yadav', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '08299832287'),
  ('GATE ATC', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '09800478180'),
  ('Hubspot', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Baramee Lertananchaikul', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('EPAM', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, NULL),
  ('Photo Solution', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Scirocco Limited', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '777308883'),
  ('Imprimerie Richard', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Industria Gráfica Cimagraf S.A.C.', 'prospect', 'pipedrive_import_2025', 'Perú', 'active', NULL, '(511)265-0453'),
  ('Quality Print Center', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '(305) 559-9854, (786) 768-6147, (305) 348-2831'),
  ('Three Z Printing', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, NULL),
  ('INTIMUS INTERNATIONAL IBERICA S.A.U.', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, '934803310'),
  ('Offsetdruk i media sp. z o. o.', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, '693 995 490'),
  ('RUSCONI TECHNOLOGY s.r.l.', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, '''+39 031 870366'),
  ('Kelley Create', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '(503) 496-7162'),
  ('Pabetechnic', 'prospect', 'pipedrive_import_2025', 'Hungary', 'active', NULL, NULL),
  ('Plot Centro', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', NULL, '''+554436231772'),
  ('Slajd', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, '''+48 500-127-217'),
  ('Data Mail, Inc.', 'prospect', 'pipedrive_import_2025', 'USA', 'active', NULL, '812.426.MAIL'),
  ('Ashirwad Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '7000545010'),
  ('Raymon', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '9443120324'),
  ('Nofal For Printing', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '00962795285678'),
  ('Taharah Shahid', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07594869771'),
  ('ches28@btinternet.com', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '020 8642 4908'),
  ('info@emmafiorentino.com.ar', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', NULL, NULL),
  ('cchapelain@yahoo.fr', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, '00 33 06 09 14 10 40'),
  ('ferkous@ideale.ma', 'prospect', 'pipedrive_import_2025', 'N. Africa', 'active', NULL, NULL),
  ('b.niemela@print.de', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, '00 49 711 44 81 70'),
  ('m.seidl@pp-europe.eu', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('a.dyck@print.de', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('dmazurek@unit.com.pl', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, '00 48 22 32 01 504'),
  ('mlkinturi@gmail.com', 'prospect', 'pipedrive_import_2025', 'Scandenavia', 'active', NULL, NULL),
  ('bobneubauer@napco.com', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('gofromagazine@gmail.com', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', NULL, NULL),
  ('sarah@proprint.com.au', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, NULL),
  ('paul@australianprinter.com.au', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, NULL),
  ('sabine@eastwest-pr.com', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('editor@globalprintmonitor.info', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('4 It Group', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, '00 39 269 27081'),
  ('Argentina Grafica Cromatica', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('AD Communications', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01372 460550, 01372 464470'),
  ('Ashville', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, '''+353 86 821 0203'),
  ('Ashville Media Group', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, '00353 1 4322231'),
  ('Birkner GmbH & Co. KG', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('Caractere', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Colourfast', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('redaction@infopresse.com', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Deutscher Drucker', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, '''+49(0)711/44817-58'),
  ('Digital Labels & Packaging magazine', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01892501382'),
  ('DEUTSCHER DRUCKER VERLAG  � eine Unit de', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL),
  ('Digital Dots', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01435 883 565'),
  ('Digital Printer', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07802 485429'),
  ('Earth Island Publishing (Print Solutions', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Earth Island', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Enviroment Times', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01257 474973'),
  ('G.S.N Raju', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Hanmail', 'prospect', 'pipedrive_import_2025', 'South Korea', 'active', NULL, NULL),
  ('selection@infopresse.com', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Gramani', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '(11) 3159 3010'),
  ('Image reports Magazine', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01932 707173'),
  ('Indian Printer and Publisher (IPP Group)', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '''+91 120 4326053'),
  ('Intelligent Media', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '0207 288 6833'),
  ('In Publishing', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01322 865984'),
  ('Indonesia Print Media', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', NULL, '62811808282'),
  ('IPW Online', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, '00 49 151 400 13586'),
  ('Redaktion@SCM.dk', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Kursiv', 'prospect', 'pipedrive_import_2025', 'Russia', 'active', NULL, NULL),
  ('Large Format Review', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01628 560891'),
  ('Labels and Labeling', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', NULL, NULL),
  ('Majalah Grafika Indonesia', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', NULL, '62811808282'),
  ('LinkPublishing', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Redaktion@Installator.dk', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Redaktion@Designbase.dk', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Redaktion@Designbase.se', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('All about newspapers', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('AGI.SE', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', NULL, NULL),
  ('Arte Grafica', 'prospect', 'pipedrive_import_2025', 'Argentina', 'active', NULL, NULL),
  ('Binstead Group', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01264 326480'),
  ('BNO', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, NULL),
  ('Banas', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', NULL, NULL),
  ('Callum Publishing', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01442 233 656'),
  ('Delhi Printer', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Comeddiance', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Draeger', 'prospect', 'pipedrive_import_2025', 'Germany', 'active', NULL, NULL)
) AS v(company_name, type, source, country, status, account_owner, phone)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



