-- Batch 13 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner, phone)
SELECT * FROM (VALUES
  ('KK Print Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '0121-454 6449'),
  ('Padnall Printers Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '020 84939475'),
  ('Slingsby', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Aston Klein Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01462 440770'),
  ('Impacked (Print & Packaging) Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '0161 4957222'),
  ('Kelsi Print', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '08714747310'),
  ('CLOC Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '020 88016983'),
  ('Richfield Print Management', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Cubic Digital', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Anglia Ruskin University', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '0845 196 2023'),
  ('Wyles Hardy & Co', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01442832234'),
  ('Marc the Printers', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '07957156955'),
  ('Technoprint', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01606 861298'),
  ('Red Design & print', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('BP Limbachix Agency', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '0775 7946 980'),
  ('Beamglow Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01480465012'),
  ('Moorprint (Ilkley)Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01943 609760'),
  ('Wow Books', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01732 373138'),
  ('Unibind UK', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Ward Imaging', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('De-Luxe Printers', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '020 89651771'),
  ('Practical Solutions Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '0117-9298180'),
  ('Pilgrim Press', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01205 356704'),
  ('Digital26', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01776704960'),
  ('University of Chester', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01244 513 222'),
  ('Kopykat Printing Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '020 77392451'),
  ('Print Ministry', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '020 88025781'),
  ('Brunel University', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01895 274000'),
  ('Edinburgh Napier University', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '0131 455 2486'),
  ('Enpress Ltd', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01794 341425'),
  ('Jaggerprint', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '020 85460593'),
  ('Kerrytype', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01730 814441'),
  ('Copy Stop', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01292 313471'),
  ('Michael Egan Associates', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '01322 445233'),
  ('Ban', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Amy', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Adam Martin', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07745957059'),
  ('Alemayehu', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Andrew', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Amir', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Barry Hamilton', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01582573471'),
  ('Andy Mackinson', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Belal', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Bharat', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Cameron Norris', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01304380941'),
  ('Chrissy Alcock', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Ciprian Andrisan', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('David Carter', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Drew Boyne', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Gareth Richards', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Gary', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Gillian Knights', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Graham', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Gina', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('''hello@peacockc, arter.co.uk''', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Ischel Singh', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01912800400'),
  ('Jason Griffin', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Jimmy Ferrufino', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('John', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Kamil Poplawski', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Jon Clark', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('John Blatchly', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '02089410144'),
  ('Kanti', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Kavan', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Kieron Bye', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07851034390'),
  ('Lauren Gilbert', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Louis', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('M Heath', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Mat', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Nick Llewellin', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01727860039'),
  ('Mike', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Patricia', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Paul', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Pete Saunders', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Paul Axton', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '020 8356 3089'),
  ('Paul Davies', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Phil Tomlinson', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Peter Schoeffler', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Poul', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Pravin', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Raj Patel', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Richard Coady', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Robert Mckee', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '01732823102'),
  ('Robert', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Rosalynn Wyatt-lambourn', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07507299035'),
  ('Sandu Popovici', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Shalab', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Shax Akram', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Sir/Madam', 'prospect', 'pipedrive_import_2025', 'Myanmar', 'active', NULL, NULL),
  ('Simon Hill', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, '07929641128'),
  ('Simon', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Steve', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Sukhwinder saify', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Steven', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Stuart', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Tinisha Zilpha Savage', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Umar', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Uzodimma Anthony', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Khalid', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', NULL, NULL),
  ('Judith Morgan', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', NULL, '01443843520')
) AS v(company_name, type, source, country, status, account_owner, phone)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



