-- Batch 43 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner, phone)
SELECT * FROM (VALUES
  ('Padraig Parker', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Pamela Anne Yasas', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Patrick', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Paul Ryder', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', NULL, '07 886-4477'),
  ('Paulo Alexandre', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, NULL),
  ('Pavel Dojacek', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', NULL, NULL),
  ('Pedro Alves', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '351 2294 77530'),
  ('Pedro Pereira', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, NULL),
  ('Pere Boada', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, NULL),
  ('Peter Karundeng', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', NULL, '082113134323'),
  ('Piotr Piotr', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, NULL),
  ('Peter Synnott', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Praga', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', NULL, NULL),
  ('Prashant Rajendra Wani', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Quamar Tahseen', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '9431481472'),
  ('Rainer', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Ramesh Vr', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Rapolas', 'prospect', 'pipedrive_import_2025', 'Lithuania', 'active', NULL, NULL),
  ('Rajesh Khatwani', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Raymond Chingwaru', 'prospect', 'pipedrive_import_2025', 'Zimbabwe', 'active', NULL, NULL),
  ('Reb Austria', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, NULL),
  ('Ricard Pijoan', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, NULL),
  ('Remzi', 'prospect', 'pipedrive_import_2025', 'turkey', 'active', NULL, NULL),
  ('Richard Pinto', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '(916)704-1226'),
  ('Rizwan Ali', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', NULL, NULL),
  ('Ricardo', 'prospect', 'pipedrive_import_2025', 'Reunion', 'active', NULL, NULL),
  ('Roger', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', NULL, NULL),
  ('Rohit kumar', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', NULL, '''-78690'),
  ('Romo Puharic', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', NULL, NULL),
  ('Ronny', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Ruben Mamo', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', NULL, NULL),
  ('Safiya Darius', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Sahebe Alam', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Samad Monsoor', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', NULL, NULL),
  ('Samir Aghallouch', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, '34641687026'),
  ('Sami', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, NULL),
  ('Salman Sadiq', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', NULL, NULL),
  ('Sandra Omeje', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', NULL, NULL),
  ('Samson', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', NULL, '0919 44 0303 329'),
  ('Samual Sene', 'prospect', 'pipedrive_import_2025', 'Papua New Guinea', 'active', NULL, NULL),
  ('Satya', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Sayed Haroun Abdelkarim', 'prospect', 'pipedrive_import_2025', 'Sudan', 'active', NULL, '249 183 462681'),
  ('Serekan Karadede', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, NULL),
  ('Sergio Ballester', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, '349 6158 8860'),
  ('Sergio Mu�oz Lopez', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, NULL),
  ('Sina Youzbashi', 'prospect', 'pipedrive_import_2025', 'Iran', 'active', NULL, NULL),
  ('Sir', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, NULL),
  ('Slah Djema�', 'prospect', 'pipedrive_import_2025', 'Tunisia', 'active', NULL, NULL),
  ('Soraisham Sanjila Chanu', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '91 8974504058'),
  ('Sunil Jain', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Subash Babu', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '''+97150 4665934'),
  ('Sushanta Kumar Jena', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Suraj Gadage', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Temu', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Teresa Branch', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Thomas Beenen', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, NULL),
  ('Thomas van der Lubbe', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, NULL),
  ('Tony Akanwa', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', NULL, NULL),
  ('Tony Hunter', 'prospect', 'pipedrive_import_2025', 'England', 'active', NULL, NULL),
  ('Utam', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Uwe Lehmann', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Vanessa Fernandes', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, NULL),
  ('Vedran Crnkovic', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', NULL, '00 385 919 210 973'),
  ('Vijay Kumar', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '09444822500'),
  ('Victor Mbiya', 'prospect', 'pipedrive_import_2025', 'Congo', 'active', NULL, NULL),
  ('Viswanathan', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, NULL),
  ('Viliam Tomascik', 'prospect', 'pipedrive_import_2025', 'Slovakia', 'active', NULL, NULL),
  ('Vitor Abreu Assis', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '351 227 128411'),
  ('Vivek Saboo', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Vivek Vatve', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '09822488386'),
  ('Vladislav Vishnevskyy', 'prospect', 'pipedrive_import_2025', 'Ukraine', 'active', NULL, NULL),
  ('Whitney Mamo', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', NULL, '''-10992'),
  ('Xishood', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('William Ordu�a', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', NULL, NULL),
  ('Winnie Obaga', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', NULL, NULL),
  ('Zdravko Velinov', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, '0896 757 006'),
  ('Yongjun', 'prospect', 'pipedrive_import_2025', 'South Korea', 'active', NULL, NULL),
  ('Zo Andriamifidisoa', 'prospect', 'pipedrive_import_2025', 'Madagascar', 'active', NULL, '2.61348E+11'),
  ('Yannick Tawali', 'prospect', 'pipedrive_import_2025', 'Cameroon', 'active', NULL, NULL),
  ('Jamia Printing Press', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', NULL, '03085004400'),
  ('Editora Damatele', 'prospect', 'pipedrive_import_2025', 'Dominican Republic', 'active', NULL, '8298301180'),
  ('Paceprint', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, '016606618'),
  ('Japak', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, '0499-577527'),
  ('National Printers', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Jorge Chipuli', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', NULL, '8119405650'),
  ('EURODISTECH SARL.', 'prospect', 'pipedrive_import_2025', 'Luxembourg', 'active', NULL, NULL),
  ('Aimpresores', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', NULL, NULL),
  ('Elanders Hungary Kft.', 'prospect', 'pipedrive_import_2025', '8999 Hungary', 'active', NULL, '''+36 30 33 00 113'),
  ('Andrew Whitson', 'prospect', 'pipedrive_import_2025', 'Northern Ireland', 'active', NULL, NULL),
  ('Reflex Graphic', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', NULL, NULL),
  ('Anand MC', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '9480442089'),
  ('Highline Office Technology', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, '0874000891'),
  ('Anand Graphics', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Smurfit Westrock', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, '087 1016788'),
  ('Vusi Masombuka', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', NULL, '082 088 8907'),
  ('ImageTech Solutions', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, '''+971 50 210 7888'),
  ('CHEVILLON IMPRIMEUR', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Over Copy', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, NULL),
  ('Shree Maa folding works', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '919924560289'),
  ('Acrialbi Acrilicos e Decorações,Lda', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '935914508')
) AS v(company_name, type, source, country, status, account_owner, phone)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



