-- Batch 42 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner, phone)
SELECT * FROM (VALUES
  ('George Wilson', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Gordon Kell', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Gregg Robinson', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', NULL, NULL),
  ('Hammad I. Alhammad', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', NULL, '''+966 50 000 5233'),
  ('Hardian Lorens', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', NULL, NULL),
  ('Harish Kumar', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Hary Iman', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', NULL, '6.28526E+12'),
  ('Hatem  Balegi', 'prospect', 'pipedrive_import_2025', 'Tunisia', 'active', NULL, NULL),
  ('Harsha Nayuni', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Herson Favis', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', NULL, NULL),
  ('Hemant', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '''+91 93207 52696'),
  ('Hesham Gouda', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', NULL, '009 66120 64417'),
  ('Hezi Keshet', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', NULL, '972 9 8870434'),
  ('Ian O''Driscoll', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', NULL, NULL),
  ('inkagraphiceditora@gmail.com', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', NULL, NULL),
  ('Ivan Espinoza', 'prospect', 'pipedrive_import_2025', 'Chile', 'active', NULL, NULL),
  ('Ivano Rizzo', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, NULL),
  ('Javier Baladron', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, NULL),
  ('Iyanar Ramapuli', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Jacobs', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Jean-Claude', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Jejo Jacob', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, '0097 33 55 00 07 7'),
  ('Jo�o Chirnev', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', NULL, NULL),
  ('Jiri Sloupensky', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', NULL, NULL),
  ('Joao Santos', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '914 593 955'),
  ('Jobi Chan', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Johan Mosq', 'prospect', 'pipedrive_import_2025', 'Latvia', 'active', NULL, NULL),
  ('Joel Daniel', 'prospect', 'pipedrive_import_2025', 'Mauritius', 'active', NULL, '23059723520'),
  ('John Smyth', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', NULL, NULL),
  ('Jon Doe', 'prospect', 'pipedrive_import_2025', 'Ghana', 'active', NULL, NULL),
  ('Joon Jo', 'prospect', 'pipedrive_import_2025', 'Korea', 'active', NULL, '82 1033203895'),
  ('Jos� Carlos Ram�rez Pacheco', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', NULL, NULL),
  ('Jones Frank', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, '(904)254-7614'),
  ('Jose Chacon', 'prospect', 'pipedrive_import_2025', 'Venezuela', 'active', NULL, NULL),
  ('Josip Rajkovic', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', NULL, NULL),
  ('''joshua_cz@hotm, ail.com''', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Jose Miguel Salazar', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', NULL, '944 522 121'),
  ('Juliet Mphanyane', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Julius Katamba', 'prospect', 'pipedrive_import_2025', 'Uganda', 'active', NULL, NULL),
  ('Junichi Iwao', 'prospect', 'pipedrive_import_2025', 'Japan', 'active', NULL, NULL),
  ('Kamel Amrioui', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('Kamel Bekkar', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('kirit bavishiya', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Klea Alliaj', 'prospect', 'pipedrive_import_2025', 'Albania', 'active', NULL, NULL),
  ('Kolawole Elegbede', 'prospect', 'pipedrive_import_2025', 'Benin', 'active', NULL, NULL),
  ('Lance Pettit', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Lahcen Benssi', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', NULL, '212 5288 98782'),
  ('Lay Naik', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Lara', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', NULL, NULL),
  ('leeann lilo', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, NULL),
  ('Linda Kempster', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, '''+61 451 713 929'),
  ('Luis Salazar', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', NULL, NULL),
  ('Luis Ferrer', 'prospect', 'pipedrive_import_2025', 'Puerto Rico', 'active', NULL, '7876017842'),
  ('Linlada Niwattanachok', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', NULL, NULL),
  ('Luqmann Ismail', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', NULL, NULL),
  ('Macarena Riveros', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, NULL),
  ('Mahesh Kumar', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Makaddesh', 'prospect', 'pipedrive_import_2025', 'China', 'active', NULL, NULL),
  ('''malcalau@hotma, il.com''', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Manish', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Manzoor ilahi khan', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Mansoor Khan', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Mansi Rao', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Manuel Pinheiro', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', NULL, '3.51964E+11'),
  ('Marcel de Boer', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, NULL),
  ('Marko Petek', 'prospect', 'pipedrive_import_2025', 'Slovenia', 'active', NULL, NULL),
  ('Marcelsoca', 'prospect', 'pipedrive_import_2025', 'Uruguay', 'active', NULL, NULL),
  ('Matt Tagle', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', NULL, NULL),
  ('Mary Pancho', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', NULL, NULL),
  ('Maroua Belorhmari', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, '0033665955931'),
  ('M�y in Th�nh Th?ng', 'prospect', 'pipedrive_import_2025', 'Vietnam', 'active', NULL, NULL),
  ('Mayank', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Mei Ann Adriano Sudiacal', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', NULL, NULL),
  ('Michael lindley', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, '61425717690'),
  ('M�ngcheng', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', NULL, NULL),
  ('mohamed lalem', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Mohamed Shafie', 'prospect', 'pipedrive_import_2025', 'Sudan', 'active', NULL, NULL),
  ('Mohammed', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', NULL, NULL),
  ('Mohamedraza Somji', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, '''+971 556507860'),
  ('MOHAMMED ALI Chalil', 'prospect', 'pipedrive_import_2025', 'Saudi Arabia', 'active', NULL, NULL),
  ('Mohammed Afsal', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Mohammed Alkafarna', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', NULL, NULL),
  ('Mr Ait Messaoud Fouad', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', NULL, '213 6614 14303'),
  ('Mufaddal Fatehi', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, NULL),
  ('Mumu', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', NULL, NULL),
  ('Muthalib Parambath', 'prospect', 'pipedrive_import_2025', 'Qatar', 'active', NULL, '''+974 33850893'),
  ('Mustafa S�zer', 'prospect', 'pipedrive_import_2025', 'Turkey', 'active', NULL, '''+90 533 655 45 94'),
  ('Natalija Kuzeva', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', NULL, NULL),
  ('Muyiwa Williams', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Nabil Raja', 'prospect', 'pipedrive_import_2025', 'Morocco', 'active', NULL, NULL),
  ('Nadia Monnier', 'prospect', 'pipedrive_import_2025', 'France', 'active', NULL, NULL),
  ('N.R. Jayaraman', 'prospect', 'pipedrive_import_2025', 'India', 'active', NULL, NULL),
  ('Nathaniel Compass', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', NULL, '19146196761'),
  ('Naveen Kumar', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Nayef Ram', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Ngozi Haynes', 'prospect', 'pipedrive_import_2025', 'Guyana', 'active', NULL, NULL),
  ('Nelson Cruz', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', NULL, NULL),
  ('Nisam Shanavas', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', NULL, NULL),
  ('Omar Nurein', 'prospect', 'pipedrive_import_2025', NULL, 'active', NULL, NULL),
  ('Oscar Friesen', 'prospect', 'pipedrive_import_2025', 'Paraguay', 'active', NULL, NULL)
) AS v(company_name, type, source, country, status, account_owner, phone)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



