
-- Batch 1 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('Count Machinery Co', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Excell Color Graphics', 'prospect', 'pipedrive_import_2025', 'U.S.A.', 'active', 'Steve Humphreys'),
  ('Jay printing', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Printlink', 'prospect', 'pipedrive_import_2025', 'Pakistan', 'active', 'Steve Humphreys'),
  ('Corporativo Grafico', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('GM Global Printing MATERIALS', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('A.R Hijjawi & Sons Co Ltd', 'prospect', 'pipedrive_import_2025', 'Palestine', 'active', 'Steve Humphreys'),
  ('Livonia', 'prospect', 'pipedrive_import_2025', 'Latvia', 'active', 'Steve Humphreys'),
  ('Golden line office', 'prospect', 'pipedrive_import_2025', '4159 Jeddah K.S.A', 'active', 'Steve Humphreys'),
  ('OM Vir Print O Pack', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Manjarrez', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('Cezanne Printing House', 'prospect', 'pipedrive_import_2025', 'Georgia', 'active', 'Steve Humphreys'),
  ('Artron s.r.o.', 'prospect', 'pipedrive_import_2025', 'Czechia', 'active', 'Steve Humphreys'),
  ('Lodha Offset Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Raval Trading', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Print house creative design & print solutions', 'prospect', 'pipedrive_import_2025', 'Cyprus', 'active', 'Steve Humphreys'),
  ('Pine Town Printers', 'prospect', 'pipedrive_import_2025', 'South Africa', 'active', 'Steve Humphreys'),
  ('Maypap', 'prospect', 'pipedrive_import_2025', 'Malaysia', 'active', 'Steve Humphreys'),
  ('Graforad', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Riverside Printers', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('New Century Press', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('Stella Print and Design', 'prospect', 'pipedrive_import_2025', 'Serbia', 'active', 'Steve Humphreys'),
  ('Maxi Grafica', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Grafische Afwerking Josuma', 'prospect', 'pipedrive_import_2025', 'Netherlands', 'active', 'Steve Humphreys'),
  ('QuickImages', 'prospect', 'pipedrive_import_2025', 'Grand Cayman', 'active', 'Steve Humphreys'),
  ('Tipăresc amintiri', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Sun Hing Printing Holdings Ltd', 'prospect', 'pipedrive_import_2025', 'Hong Kong', 'active', 'Steve Humphreys'),
  ('MDVDDFUS', 'prospect', 'pipedrive_import_2025', 'Israel', 'active', 'Steve Humphreys'),
  ('Mohamed Khalil', 'prospect', 'pipedrive_import_2025', 'United Arab Emirates', 'active', 'Steve Humphreys'),
  ('Anand Xerox', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Grafoprom design and print house', 'prospect', 'pipedrive_import_2025', 'North Macedonia', 'active', 'Steve Humphreys'),
  ('Dwight Williams', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('The Copy Shop', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('KEN WILKINS PRINT LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Print Expert', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PrimeTech Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PRINT DESIGN & SIGN LTD', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Seventy9 Website Design Print & Digital Marketing', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PMG Print Management', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Aura Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('HAD-PRINT', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Route 1 Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Gemini Print Group', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Jack Harris'),
  ('Print 4 Business Ltd', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('GBF Labels Print & Packaging', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Dominion Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Jack Harris'),
  ('Potts Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('OASTHOUSE MARKETING DESIGN AND PRINT LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('REDTREE PRINT SOLUTIONS LTD.', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Print-Tech Solutions Ltd', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PRINT UK LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('SLS Print Limited - London - UK', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Independent Print Industries Association', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PSL Print Management', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Gold Design Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Jack Harris'),
  ('PRE-PRINT TECHNOLOGY LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('County Print Finishers', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Bayan Group', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Rusconitechnology', 'prospect', 'pipedrive_import_2025', 'Italy', 'active', 'Steve Humphreys'),
  ('JDC Priting Tech Sri Lanka', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('G.K. Print House Pvt. Ltd', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Fabrifolder', 'prospect', 'pipedrive_import_2025', 'Colombia', 'active', 'Steve Humphreys'),
  ('Tuicial', 'prospect', 'pipedrive_import_2025', 'Brazil', 'active', 'Steve Humphreys'),
  ('Max Copy Center', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('E7 Printing', 'prospect', 'pipedrive_import_2025', 'U.A.E', 'active', 'Steve Humphreys'),
  ('Socios', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Imprensa National', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('My Prints.co.ke', 'prospect', 'pipedrive_import_2025', 'Kenya', 'active', 'Steve Humphreys'),
  ('Printech Machineries', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('PMWEB Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Graphic Arts Group | Sign & Display | Corporate Print | Promotional Merchandise | Labels', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Banner Box Print Solutions', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Wallace Print', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('The Print Magician', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('NAVILLUS PRINT GIFTS LIMITED', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Spin Print Solutions', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Olympus Print Group Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Jack Harris'),
  ('LT Print Group', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('PAPCOM Digital Print Ltd', 'prospect', 'pipedrive_import_2025', 'United Kingdom', 'active', 'Jack Harris'),
  ('Duuilo Oy', 'prospect', 'pipedrive_import_2025', 'Finland', 'active', 'Steve Humphreys'),
  ('Kruno Ivanković', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Imprimerie Papeterie du Congo', 'prospect', 'pipedrive_import_2025', 'Congo', 'active', 'Steve Humphreys'),
  ('MGX Digital', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Auckland Copy Shop', 'prospect', 'pipedrive_import_2025', 'New Zealand', 'active', 'Steve Humphreys'),
  ('RedPanda', 'prospect', 'pipedrive_import_2025', 'Kazakhstan', 'active', 'Steve Humphreys'),
  ('Barbara Middleton', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('John Nixon', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Sadek Group', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('MVL Valletta Ltd', 'prospect', 'pipedrive_import_2025', 'Malta', 'active', 'Steve Humphreys'),
  ('Master Kina', 'prospect', 'pipedrive_import_2025', 'Egypt', 'active', 'Steve Humphreys'),
  ('The Mail Haus, Inc', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Kenlis Trading', 'prospect', 'pipedrive_import_2025', 'Namibia', 'active', 'Steve Humphreys'),
  ('Orchid', 'prospect', 'pipedrive_import_2025', 'Sultanate of Oman', 'active', 'Steve Humphreys'),
  ('Staffordshire Printing Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Modern Technology', 'prospect', 'pipedrive_import_2025', 'Bangladesh', 'active', 'Steve Humphreys'),
  ('Jose David Valle', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Seana Giles', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Gaétan Mahé Photographies', 'prospect', 'pipedrive_import_2025', 'France', 'active', 'Steve Humphreys'),
  ('Ricardo Chung', 'prospect', 'pipedrive_import_2025', 'Panama', 'active', 'Steve Humphreys'),
  ('Snap Campbelltown', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys')
) AS v(company_name, type, source, country, status, account_owner)
WHERE NOT EXISTS (
  SELECT 1 FROM companies
  WHERE LOWER(TRIM(companies.company_name)) = LOWER(TRIM(v.company_name))
);



-- Batch 2 of 47
INSERT INTO companies (company_name, type, source, country, status, account_owner)
SELECT * FROM (VALUES
  ('FD COMPREHENSIVE PRINTING SERVICES', 'prospect', 'pipedrive_import_2025', 'Mexico', 'active', 'Steve Humphreys'),
  ('S.Sifraj', 'prospect', 'pipedrive_import_2025', 'Sri Lanka', 'active', 'Steve Humphreys'),
  ('Yonnette Fredericks-Belle', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Craigrossie Printing', 'prospect', 'pipedrive_import_2025', 'Scotland', 'active', 'Steve Humphreys'),
  ('Minuteman Press Madison', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('J Studios', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('RR Donnelley Illinois', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Fast Advertisement LTD.', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Laquita Morris', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Studio Graphics Corporation', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Amster Printing Service', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Express Numerique', 'prospect', 'pipedrive_import_2025', 'Tunisia', 'active', 'Steve Humphreys'),
  ('Inkhead Printing Services', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Andrew Liew', 'prospect', 'pipedrive_import_2025', 'Philippines', 'active', 'Steve Humphreys'),
  ('Comunicación Visual', 'prospect', 'pipedrive_import_2025', 'Peru', 'active', 'Steve Humphreys'),
  ('The UK Factory Ltd.', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Belmonte Printing Co.', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Ahmad Mubarrok', 'prospect', 'pipedrive_import_2025', 'Indonesia', 'active', 'Steve Humphreys'),
  ('Love From Aunty Helen', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('DHS Enterprises Pte Ltd', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Singapore Polytechnic', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Network Press', 'prospect', 'pipedrive_import_2025', 'Australia', 'active', 'Steve Humphreys'),
  ('Scandinavian Print Group Polska Sp. z o.o', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('The Angelus Press Ltd.', 'prospect', 'pipedrive_import_2025', 'Belize', 'active', 'Steve Humphreys'),
  ('Fuji Seal Packaging (Thailand) Co., Ltd', 'prospect', 'pipedrive_import_2025', 'Thailand', 'active', 'Steve Humphreys'),
  ('Peter Stanek', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printers World', 'prospect', 'pipedrive_import_2025', 'Malawi', 'active', 'Steve Humphreys'),
  ('Drukkerij Hendrix', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Aung Ko Ko Ye', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Bejdzor Halmati', 'prospect', 'pipedrive_import_2025', 'Czech Republic', 'active', 'Steve Humphreys'),
  ('Dennison Press & Design LLC', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Go Local Magazine & Print Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Ultimate Products', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Printabulous Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('British Vintage Posters', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Inkthreadable', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Papertogether', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Northern Print Management Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Amos Communications, Inc.', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Tableau Reproduction Ltd.', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Odutola Tola', 'prospect', 'pipedrive_import_2025', 'Nigeria', 'active', 'Steve Humphreys'),
  ('Baba Ali Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Symbiosys pls', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Cleddau Press', 'prospect', 'pipedrive_import_2025', 'Wales', 'active', 'Steve Humphreys'),
  ('Minuteman Press Basingstoke', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Nevex Printing Centre', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print n Go', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('FERO Retail Marketing', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Imperial Clinical Research Services', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Naili Print Media', 'prospect', 'pipedrive_import_2025', 'Singapore', 'active', 'Steve Humphreys'),
  ('Brookstone Ltd.', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Jack Harris'),
  ('Sarl ATLANTIS', 'prospect', 'pipedrive_import_2025', 'Algeria', 'active', 'Steve Humphreys'),
  ('Impressions', 'prospect', 'pipedrive_import_2025', 'India', 'active', 'Steve Humphreys'),
  ('Print Plus', 'prospect', 'pipedrive_import_2025', 'Ireland', 'active', 'Steve Humphreys'),
  ('Dijiland', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Steve Humphreys'),
  ('Tattnall Printing', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Technifold', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Jack Harris'),
  ('Fordingbridge Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('André Preguiça', 'prospect', 'pipedrive_import_2025', 'Portugal', 'active', 'Steve Humphreys'),
  ('Crossbow Printing', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('A14 Print', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Azdar Press sc M. Gromaszek D. Jemielniak', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Data Communications Management', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Eye On Display', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Mark', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Rapidity London', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Directors Advantage, Inc.', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Oman Printers and Stationers. Co. L.L.C', 'prospect', 'pipedrive_import_2025', 'Oman', 'active', 'Steve Humphreys'),
  ('Digital Printing Systems UK Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Walstead Roche unit 11', 'prospect', 'pipedrive_import_2025', NULL, 'active', 'Jack Harris'),
  ('Rapidity Sidcup', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('TipoMedia', 'prospect', 'pipedrive_import_2025', 'Romania', 'active', 'Steve Humphreys'),
  ('Printed.com', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Print Your Imagination', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('The Perfect Match UK', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('Safran Electrical & Power', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('KNOWNO LLC', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Sirijus grafika d.o.o.', 'prospect', 'pipedrive_import_2025', 'Croatia', 'active', 'Steve Humphreys'),
  ('Graficas Sagrera', 'prospect', 'pipedrive_import_2025', 'Spain', 'active', 'Steve Humphreys'),
  ('Book Lovers'' Press', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
  ('WOLFRATECH', 'prospect', 'pipedrive_import_2025', 'Poland', 'active', 'Steve Humphreys'),
  ('Red Cactus', 'prospect', 'pipedrive_import_2025', 'Belgium', 'active', 'Steve Humphreys'),
  ('Davis Direct', 'prospect', 'pipedrive_import_2025', 'USA', 'active', 'Steve Humphreys'),
  ('Svenskt stearin', 'prospect', 'pipedrive_import_2025', 'Sweden', 'active', 'Steve Humphreys'),
  ('Hunts England Ltd', 'prospect', 'pipedrive_import_2025', 'England', 'active', 'Steve Humphreys'),
